#pragma once
#include "pixels.h"

namespace MilitaryAvoid {

	using namespace System;
	using namespace System::ComponentModel;
	using namespace System::Collections;
	using namespace System::Windows::Forms;
	using namespace System::Data;
	using namespace System::Drawing;
	using namespace System::Drawing::Drawing2D;

	/// <summary>
	/// —водка дл€ MyForm
	/// </summary>
	public ref class MilitaryAvoidForm : public System::Windows::Forms::Form
	{
	public:
		MilitaryAvoidForm(void)
		{
			InitializeComponent();
			//
			//TODO: добавьте код конструктора
			//
		}

	protected:
		/// <summary>
		/// ќсвободить все используемые ресурсы.
		/// </summary>
		~MilitaryAvoidForm()
		{
			if (components)
			{
				delete components;
			}
		}
	public: System::Windows::Forms::PictureBox^ PB_Playboard;
	protected:

	protected:

	private:
		/// <summary>
		/// ќб€зательна€ переменна€ конструктора.
		/// </summary>
		System::ComponentModel::Container ^components;

#pragma region Windows Form Designer generated code
		/// <summary>
		/// “ребуемый метод дл€ поддержки конструктора Ч не измен€йте 
		/// содержимое этого метода с помощью редактора кода.
		/// </summary>
		void InitializeComponent(void)
		{
			this->PB_Playboard = (gcnew System::Windows::Forms::PictureBox());
			(cli::safe_cast<System::ComponentModel::ISupportInitialize^>(this->PB_Playboard))->BeginInit();
			this->SuspendLayout();
			// 
			// PB_Playboard
			// 
			this->PB_Playboard->Location = System::Drawing::Point(0, 0);
			this->PB_Playboard->Name = L"PB_Playboard";
			this->PB_Playboard->Size = System::Drawing::Size(159, 105);
			this->PB_Playboard->TabIndex = 0;
			this->PB_Playboard->TabStop = false;
			this->PB_Playboard->Paint += gcnew System::Windows::Forms::PaintEventHandler(this, &MilitaryAvoidForm::PB_Playboard_Paint);
			this->PB_Playboard->MouseMove += gcnew System::Windows::Forms::MouseEventHandler(this, &MilitaryAvoidForm::PB_Playboard_MouseMove);
			// 
			// MilitaryAvoidForm
			// 
			this->AutoScaleDimensions = System::Drawing::SizeF(6, 13);
			this->AutoScaleMode = System::Windows::Forms::AutoScaleMode::Font;
			this->ClientSize = System::Drawing::Size(948, 524);
			this->Controls->Add(this->PB_Playboard);
			this->Name = L"MilitaryAvoidForm";
			this->StartPosition = System::Windows::Forms::FormStartPosition::CenterScreen;
			this->Text = L"MilitaryAvoid";
			this->WindowState = System::Windows::Forms::FormWindowState::Maximized;
			this->Load += gcnew System::EventHandler(this, &MilitaryAvoidForm::MilitaryAvoidForm_Load);
			this->SizeChanged += gcnew System::EventHandler(this, &MilitaryAvoidForm::MilitaryAvoidForm_SizeChanged);
			(cli::safe_cast<System::ComponentModel::ISupportInitialize^>(this->PB_Playboard))->EndInit();
			this->ResumeLayout(false);

		}
#pragma endregion
		
		public: System::Void draw() {
			const int x_border = 25;
			const int y_border = 25;
			//const int x_aspect = 890;
			//const int y_aspect = 510;
			const float aspect = 510.0f / 890.0f;
			int width = this->Width - x_border * 2 - 20;
			int height = this->Height - y_border * 2 - 39;
			float real_aspect = (float)height / (float)width;
			Point* center = new Point((this->Width - 20) / 2, (this->Height - 39) / 2);
			//Point** workspace = new Point*;
			
			if (real_aspect > aspect) {
				int new_height = width * aspect;
				workspace[0] = new Point(x_border, center->Y - new_height / 2);
				workspace[1] = new Point(x_border + width, center->Y + new_height / 2);
			}
			else {
				int new_width = height / aspect;
				workspace[0] = new Point(center->X - new_width / 2, y_border);
				workspace[1] = new Point(center->X + new_width / 2, y_border + height);
			}
			ratio_x = (float)(workspace[1]->X - workspace[0]->X) / 890;
			ratio_y = (float)(workspace[1]->Y - workspace[0]->Y) / 510;


			PB_Playboard->Width = this->Width;
			PB_Playboard->Height = this->Height;
			//Bitmap^ board = gcnew Bitmap(PB_Playboard->Width, PB_Playboard->Height);
			//Graphics^ grfx = Graphics::FromImage(board);
			////Drawing background
			//grfx->Clear(Color::FromArgb(205, 205, 205));
			//Rectangle* rect = new Rectangle(
			//	workspace[0]->X, workspace[0]->Y,
			//	-workspace[0]->X + workspace[1]->X, -workspace[0]->Y + workspace[1]->Y);
			//PointF* p1 = new PointF(workspace[0]->X, workspace[0]->Y);
			//PointF* p2 = new PointF(-workspace[0]->X + workspace[1]->X, -workspace[0]->Y + workspace[1]->Y);
			//LinearGradientBrush^ russia_grad = gcnew LinearGradientBrush(*p1, *p2,
			//	Color::Aqua, Color::BlueViolet);

			//GraphicsPath^ path = gcnew GraphicsPath();
			////path->AddEllipse(0, 0, 140, 70);
			//path->AddRectangle(*rect);
			//PathGradientBrush^ pthGrBrush = gcnew PathGradientBrush(path);
			//pthGrBrush->CenterColor = Color::FromArgb(255, 20, 255, 30);
			//pthGrBrush->CenterPoint = this->Cursor->Position;
			//array<Color>^ colors = { 
			//	Color::FromArgb(255, 0, 255, 255),
			//	Color::FromArgb(255, 0, 200, 255) 
			//};
			//pthGrBrush->SurroundColors = colors;


			////PathGradientBrush^ rg = gcnew PathGradientBrush();
			//grfx->FillRectangle(pthGrBrush, workspace[0]->X, workspace[0]->Y,
			//	-workspace[0]->X + workspace[1]->X, -workspace[0]->Y + workspace[1]->Y);
			//array<Point>^ Russia = { 
			//	Point (workspace[0]->X + 784 * ratio_x, workspace[0]->Y + 4 * ratio_y),
			//	Point (workspace[0]->X + 789 * ratio_x, workspace[0]->Y + 8 * ratio_y),
			//	Point (workspace[0]->X + 787 * ratio_x, workspace[0]->Y + 11 * ratio_y),
			//	Point(workspace[0]->X + 791 * ratio_x, workspace[0]->Y + 13 * ratio_y),
			//	Point(workspace[0]->X + 787 * ratio_x, workspace[0]->Y + 17 * ratio_y),
			//	Point(workspace[0]->X + 794 * ratio_x, workspace[0]->Y + 17 * ratio_y),
			//	Point(workspace[0]->X + 802 * ratio_x, workspace[0]->Y + 26 * ratio_y),
			//	Point(workspace[0]->X + 796 * ratio_x, workspace[0]->Y + 29 * ratio_y),
			//	Point(workspace[0]->X + 793 * ratio_x, workspace[0]->Y + 35 * ratio_y),
			//	Point(workspace[0]->X + 786 * ratio_x, workspace[0]->Y + 34 * ratio_y),
			//	Point(workspace[0]->X + 784 * ratio_x, workspace[0]->Y + 44 * ratio_y),
			//	Point(workspace[0]->X + 777 * ratio_x, workspace[0]->Y + 45 * ratio_y),
			//	Point(workspace[0]->X + 773 * ratio_x, workspace[0]->Y + 44 * ratio_y),
			//	Point(workspace[0]->X + 775 * ratio_x, workspace[0]->Y + 53 * ratio_y),
			//	Point(workspace[0]->X + 782 * ratio_x, workspace[0]->Y + 54 * ratio_y),
			//	Point(workspace[0]->X + 786 * ratio_x, workspace[0]->Y + 58 * ratio_y),
			//	Point(workspace[0]->X + 788 * ratio_x, workspace[0]->Y + 67 * ratio_y),
			//	Point(workspace[0]->X + 781 * ratio_x, workspace[0]->Y + 71 * ratio_y)
			//};
			//grfx->FillPolygon(Brushes::Green, Russia);
			//this->Text = ratio_x.ToString();
			//PB_Playboard->Image = board;
			paint();
			delete center;
			//delete workspace[1];
			//delete workspace[2]; 
			//delete[] workspace;
		}

		public: System::Void paint() {
			Bitmap^ board = gcnew Bitmap(PB_Playboard->Width, PB_Playboard->Height);
			Graphics^ grfx = Graphics::FromImage(board);
			//Drawing background
			grfx->Clear(Color::FromArgb(205, 205, 205));
			Rectangle* rect = new Rectangle(
				workspace[0]->X, workspace[0]->Y,
				-workspace[0]->X + workspace[1]->X, -workspace[0]->Y + workspace[1]->Y);
			PointF* p1 = new PointF(workspace[0]->X, workspace[0]->Y);
			PointF* p2 = new PointF(-workspace[0]->X + workspace[1]->X, -workspace[0]->Y + workspace[1]->Y);
			LinearGradientBrush^ russia_grad = gcnew LinearGradientBrush(*p1, *p2,
				Color::Aqua, Color::BlueViolet);

			GraphicsPath^ path = gcnew GraphicsPath();
			//path->AddEllipse(0, 0, 140, 70);
			path->AddRectangle(*rect);
			PathGradientBrush^ pthGrBrush = gcnew PathGradientBrush(path);
			pthGrBrush->CenterColor = Color::FromArgb(255, 20, 255, 30);
			pthGrBrush->CenterPoint = this->Cursor->Position;
			array<Color>^ colors = {
				Color::FromArgb(255, 0, 255, 255),
				Color::FromArgb(255, 0, 200, 255)
			};
			pthGrBrush->SurroundColors = colors;
			SolidBrush^ bg = gcnew SolidBrush(Color::FromArgb(205, 205, 205));

			//PathGradientBrush^ rg = gcnew PathGradientBrush();
			grfx->FillRectangle(pthGrBrush, workspace[0]->X, workspace[0]->Y,
				-workspace[0]->X + workspace[1]->X, -workspace[0]->Y + workspace[1]->Y);
			array<Point>^ Russia0 = {
				Point(workspace[1]->X, workspace[0]->Y + 3 * ratio_y),
				Point(workspace[0]->X + 780 * ratio_x, workspace[0]->Y + 3 * ratio_y),
				Point(workspace[0]->X + 781 * ratio_x, workspace[0]->Y + 5 * ratio_y),
				Point(workspace[0]->X + 782 * ratio_x, workspace[0]->Y + 6 * ratio_y),
				Point(workspace[0]->X + 783 * ratio_x, workspace[0]->Y + 7 * ratio_y),
				Point(workspace[0]->X + 784 * ratio_x, workspace[0]->Y + 9 * ratio_y),
				Point(workspace[0]->X + 783 * ratio_x, workspace[0]->Y + 10 * ratio_y),
				Point(workspace[0]->X + 786 * ratio_x, workspace[0]->Y + 11 * ratio_y),
				Point(workspace[0]->X + 786 * ratio_x, workspace[0]->Y + 14 * ratio_y),
				Point(workspace[0]->X + 784 * ratio_x, workspace[0]->Y + 15 * ratio_y),
				Point(workspace[0]->X + 783 * ratio_x, workspace[0]->Y + 16 * ratio_y),
				Point(workspace[0]->X + 784 * ratio_x, workspace[0]->Y + 18 * ratio_y),
				Point(workspace[0]->X + 786 * ratio_x, workspace[0]->Y + 17 * ratio_y),
				Point(workspace[0]->X + 788 * ratio_x, workspace[0]->Y + 17 * ratio_y),
				Point(workspace[0]->X + 789 * ratio_x, workspace[0]->Y + 17 * ratio_y),
				Point(workspace[0]->X + 792 * ratio_x, workspace[0]->Y + 18 * ratio_y),
				Point(workspace[0]->X + 793 * ratio_x, workspace[0]->Y + 20 * ratio_y),
				Point(workspace[0]->X + 794 * ratio_x, workspace[0]->Y + 21 * ratio_y),
				Point(workspace[0]->X + 796 * ratio_x, workspace[0]->Y + 21 * ratio_y),
				Point(workspace[0]->X + 796 * ratio_x, workspace[0]->Y + 21 * ratio_y),
				Point(workspace[0]->X + 795 * ratio_x, workspace[0]->Y + 23 * ratio_y),
				Point(workspace[0]->X + 796 * ratio_x, workspace[0]->Y + 24 * ratio_y),
				Point(workspace[0]->X + 796 * ratio_x, workspace[0]->Y + 26 * ratio_y),
				Point(workspace[0]->X + 795 * ratio_x, workspace[0]->Y + 27 * ratio_y),
				Point(workspace[0]->X + 792 * ratio_x, workspace[0]->Y + 27 * ratio_y),
				Point(workspace[0]->X + 791 * ratio_x, workspace[0]->Y + 30 * ratio_y),
				Point(workspace[0]->X + 789 * ratio_x, workspace[0]->Y + 34 * ratio_y),
				Point(workspace[0]->X + 789 * ratio_x, workspace[0]->Y + 34 * ratio_y),
				Point(workspace[0]->X + 785 * ratio_x, workspace[0]->Y + 34 * ratio_y),
				Point(workspace[0]->X + 783 * ratio_x, workspace[0]->Y + 34 * ratio_y),
				Point(workspace[0]->X + 781 * ratio_x, workspace[0]->Y + 34 * ratio_y),
				Point(workspace[0]->X + 779 * ratio_x, workspace[0]->Y + 35 * ratio_y),
				Point(workspace[0]->X + 779 * ratio_x, workspace[0]->Y + 37 * ratio_y),
				Point(workspace[0]->X + 779 * ratio_x, workspace[0]->Y + 40 * ratio_y),
				Point(workspace[0]->X + 779 * ratio_x, workspace[0]->Y + 41 * ratio_y),
				Point(workspace[0]->X + 779 * ratio_x, workspace[0]->Y + 43 * ratio_y),
				Point(workspace[0]->X + 778 * ratio_x, workspace[0]->Y + 44 * ratio_y),
				Point(workspace[0]->X + 776 * ratio_x, workspace[0]->Y + 44 * ratio_y),
				Point(workspace[0]->X + 772 * ratio_x, workspace[0]->Y + 45 * ratio_y),
				Point(workspace[0]->X + 770 * ratio_x, workspace[0]->Y + 45 * ratio_y),
				Point(workspace[0]->X + 770 * ratio_x, workspace[0]->Y + 44 * ratio_y),
				Point(workspace[0]->X + 768 * ratio_x, workspace[0]->Y + 43 * ratio_y),
				Point(workspace[0]->X + 768 * ratio_x, workspace[0]->Y + 46 * ratio_y),
				Point(workspace[0]->X + 768 * ratio_x, workspace[0]->Y + 49 * ratio_y),
				Point(workspace[0]->X + 770 * ratio_x, workspace[0]->Y + 50 * ratio_y),
				Point(workspace[0]->X + 771 * ratio_x, workspace[0]->Y + 51 * ratio_y),
				Point(workspace[0]->X + 774 * ratio_x, workspace[0]->Y + 51 * ratio_y),
				Point(workspace[0]->X + 776 * ratio_x, workspace[0]->Y + 52 * ratio_y),
				Point(workspace[0]->X + 778 * ratio_x, workspace[0]->Y + 53 * ratio_y),
				Point(workspace[0]->X + 780 * ratio_x, workspace[0]->Y + 54 * ratio_y),
				Point(workspace[0]->X + 781 * ratio_x, workspace[0]->Y + 56 * ratio_y),
				Point(workspace[0]->X + 782 * ratio_x, workspace[0]->Y + 57 * ratio_y),
				Point(workspace[0]->X + 783 * ratio_x, workspace[0]->Y + 59 * ratio_y),
				Point(workspace[0]->X + 783 * ratio_x, workspace[0]->Y + 60 * ratio_y),
				Point(workspace[0]->X + 783 * ratio_x, workspace[0]->Y + 62 * ratio_y),
				Point(workspace[0]->X + 783 * ratio_x, workspace[0]->Y + 65 * ratio_y),
				Point(workspace[0]->X + 782 * ratio_x, workspace[0]->Y + 66 * ratio_y),
				Point(workspace[0]->X + 779 * ratio_x, workspace[0]->Y + 67 * ratio_y),
				Point(workspace[0]->X + 778 * ratio_x, workspace[0]->Y + 68 * ratio_y),
				Point(workspace[0]->X + 776 * ratio_x, workspace[0]->Y + 68 * ratio_y),
				Point(workspace[0]->X + 776 * ratio_x, workspace[0]->Y + 70 * ratio_y),
				Point(workspace[0]->X + 777 * ratio_x, workspace[0]->Y + 72 * ratio_y),
				Point(workspace[0]->X + 778 * ratio_x, workspace[0]->Y + 73 * ratio_y),
				Point(workspace[0]->X + 780 * ratio_x, workspace[0]->Y + 73 * ratio_y),
				Point(workspace[0]->X + 781 * ratio_x, workspace[0]->Y + 70 * ratio_y),
				Point(workspace[0]->X + 782 * ratio_x, workspace[0]->Y + 69 * ratio_y),
				Point(workspace[0]->X + 784 * ratio_x, workspace[0]->Y + 69 * ratio_y),
				Point(workspace[0]->X + 786 * ratio_x, workspace[0]->Y + 69 * ratio_y),
				Point(workspace[0]->X + 786 * ratio_x, workspace[0]->Y + 67 * ratio_y),
				Point(workspace[0]->X + 788 * ratio_x, workspace[0]->Y + 66 * ratio_y),
				Point(workspace[0]->X + 792 * ratio_x, workspace[0]->Y + 66 * ratio_y),
				Point(workspace[0]->X + 793 * ratio_x, workspace[0]->Y + 66 * ratio_y),
				Point(workspace[0]->X + 794 * ratio_x, workspace[0]->Y + 67 * ratio_y),
				Point(workspace[0]->X + 796 * ratio_x, workspace[0]->Y + 68 * ratio_y),
				Point(workspace[0]->X + 798 * ratio_x, workspace[0]->Y + 67 * ratio_y),
				Point(workspace[0]->X + 799 * ratio_x, workspace[0]->Y + 66 * ratio_y),
				Point(workspace[0]->X + 800 * ratio_x, workspace[0]->Y + 66 * ratio_y),
				Point(workspace[0]->X + 802 * ratio_x, workspace[0]->Y + 65 * ratio_y),
				Point(workspace[0]->X + 803 * ratio_x, workspace[0]->Y + 65 * ratio_y),
				Point(workspace[0]->X + 805 * ratio_x, workspace[0]->Y + 66 * ratio_y),
				Point(workspace[0]->X + 807 * ratio_x, workspace[0]->Y + 65 * ratio_y),
				Point(workspace[0]->X + 808 * ratio_x, workspace[0]->Y + 67 * ratio_y),
				Point(workspace[0]->X + 810 * ratio_x, workspace[0]->Y + 69 * ratio_y),
				Point(workspace[0]->X + 809 * ratio_x, workspace[0]->Y + 71 * ratio_y),
				Point(workspace[0]->X + 807 * ratio_x, workspace[0]->Y + 72 * ratio_y),
				Point(workspace[0]->X + 806 * ratio_x, workspace[0]->Y + 75 * ratio_y),
				Point(workspace[0]->X + 803 * ratio_x, workspace[0]->Y + 76 * ratio_y),
				Point(workspace[0]->X + 803 * ratio_x, workspace[0]->Y + 77 * ratio_y),
				Point(workspace[0]->X + 803 * ratio_x, workspace[0]->Y + 79 * ratio_y),
				Point(workspace[0]->X + 804 * ratio_x, workspace[0]->Y + 81 * ratio_y),
				Point(workspace[0]->X + 805 * ratio_x, workspace[0]->Y + 83 * ratio_y),
				Point(workspace[0]->X + 806 * ratio_x, workspace[0]->Y + 85 * ratio_y),
				Point(workspace[0]->X + 806 * ratio_x, workspace[0]->Y + 87 * ratio_y),
				Point(workspace[0]->X + 806 * ratio_x, workspace[0]->Y + 89 * ratio_y),
				Point(workspace[0]->X + 807 * ratio_x, workspace[0]->Y + 90 * ratio_y),
				Point(workspace[0]->X + 807 * ratio_x, workspace[0]->Y + 92 * ratio_y),
				Point(workspace[0]->X + 807 * ratio_x, workspace[0]->Y + 95 * ratio_y),
				Point(workspace[0]->X + 807 * ratio_x, workspace[0]->Y + 96 * ratio_y),
				Point(workspace[0]->X + 808 * ratio_x, workspace[0]->Y + 99 * ratio_y),
				Point(workspace[0]->X + 808 * ratio_x, workspace[0]->Y + 101 * ratio_y),
				Point(workspace[0]->X + 809 * ratio_x, workspace[0]->Y + 102 * ratio_y),
				Point(workspace[0]->X + 810 * ratio_x, workspace[0]->Y + 105 * ratio_y),
				Point(workspace[0]->X + 811 * ratio_x, workspace[0]->Y + 108 * ratio_y),
				Point(workspace[0]->X + 812 * ratio_x, workspace[0]->Y + 110 * ratio_y),
				Point(workspace[0]->X + 813 * ratio_x, workspace[0]->Y + 111 * ratio_y),
				Point(workspace[0]->X + 813 * ratio_x, workspace[0]->Y + 114 * ratio_y),
				Point(workspace[0]->X + 813 * ratio_x, workspace[0]->Y + 116 * ratio_y),
				Point(workspace[0]->X + 813 * ratio_x, workspace[0]->Y + 117 * ratio_y),
				Point(workspace[0]->X + 814 * ratio_x, workspace[0]->Y + 119 * ratio_y),
				Point(workspace[0]->X + 815 * ratio_x, workspace[0]->Y + 120 * ratio_y),
				Point(workspace[0]->X + 816 * ratio_x, workspace[0]->Y + 122 * ratio_y),
				Point(workspace[0]->X + 817 * ratio_x, workspace[0]->Y + 124 * ratio_y),
				Point(workspace[0]->X + 818 * ratio_x, workspace[0]->Y + 125 * ratio_y),
				Point(workspace[0]->X + 817 * ratio_x, workspace[0]->Y + 126 * ratio_y),
				Point(workspace[0]->X + 817 * ratio_x, workspace[0]->Y + 126 * ratio_y),
				Point(workspace[0]->X + 814 * ratio_x, workspace[0]->Y + 127 * ratio_y),
				Point(workspace[0]->X + 813 * ratio_x, workspace[0]->Y + 128 * ratio_y),
				Point(workspace[0]->X + 811 * ratio_x, workspace[0]->Y + 128 * ratio_y),
				Point(workspace[0]->X + 810 * ratio_x, workspace[0]->Y + 131 * ratio_y),
				Point(workspace[0]->X + 809 * ratio_x, workspace[0]->Y + 133 * ratio_y),
				Point(workspace[0]->X + 807 * ratio_x, workspace[0]->Y + 135 * ratio_y),
				Point(workspace[0]->X + 807 * ratio_x, workspace[0]->Y + 136 * ratio_y),
				Point(workspace[0]->X + 807 * ratio_x, workspace[0]->Y + 139 * ratio_y),
				Point(workspace[0]->X + 807 * ratio_x, workspace[0]->Y + 141 * ratio_y),
				Point(workspace[0]->X + 807 * ratio_x, workspace[0]->Y + 143 * ratio_y),
				Point(workspace[0]->X + 808 * ratio_x, workspace[0]->Y + 145 * ratio_y),
				Point(workspace[0]->X + 809 * ratio_x, workspace[0]->Y + 148 * ratio_y),
				Point(workspace[0]->X + 807 * ratio_x, workspace[0]->Y + 147 * ratio_y),
				Point(workspace[0]->X + 804 * ratio_x, workspace[0]->Y + 146 * ratio_y),
				Point(workspace[0]->X + 803 * ratio_x, workspace[0]->Y + 146 * ratio_y),
				Point(workspace[0]->X + 803 * ratio_x, workspace[0]->Y + 148 * ratio_y),
				Point(workspace[0]->X + 805 * ratio_x, workspace[0]->Y + 150 * ratio_y),
				Point(workspace[0]->X + 805 * ratio_x, workspace[0]->Y + 152 * ratio_y),
				Point(workspace[0]->X + 806 * ratio_x, workspace[0]->Y + 154 * ratio_y),
				Point(workspace[0]->X + 805 * ratio_x, workspace[0]->Y + 155 * ratio_y),
				Point(workspace[0]->X + 804 * ratio_x, workspace[0]->Y + 155 * ratio_y),
				Point(workspace[0]->X + 802 * ratio_x, workspace[0]->Y + 157 * ratio_y),
				Point(workspace[0]->X + 803 * ratio_x, workspace[0]->Y + 157 * ratio_y),
				Point(workspace[0]->X + 803 * ratio_x, workspace[0]->Y + 159 * ratio_y),
				Point(workspace[0]->X + 802 * ratio_x, workspace[0]->Y + 160 * ratio_y),
				Point(workspace[0]->X + 802 * ratio_x, workspace[0]->Y + 162 * ratio_y),
				Point(workspace[0]->X + 803 * ratio_x, workspace[0]->Y + 165 * ratio_y),
				Point(workspace[0]->X + 804 * ratio_x, workspace[0]->Y + 166 * ratio_y),
				Point(workspace[0]->X + 806 * ratio_x, workspace[0]->Y + 168 * ratio_y),
				Point(workspace[0]->X + 808 * ratio_x, workspace[0]->Y + 169 * ratio_y),
				Point(workspace[0]->X + 810 * ratio_x, workspace[0]->Y + 171 * ratio_y),
				Point(workspace[0]->X + 810 * ratio_x, workspace[0]->Y + 172 * ratio_y),
				Point(workspace[0]->X + 810 * ratio_x, workspace[0]->Y + 174 * ratio_y),
				Point(workspace[0]->X + 810 * ratio_x, workspace[0]->Y + 176 * ratio_y),
				Point(workspace[0]->X + 810 * ratio_x, workspace[0]->Y + 178 * ratio_y),
				Point(workspace[0]->X + 812 * ratio_x, workspace[0]->Y + 179 * ratio_y),
				Point(workspace[0]->X + 814 * ratio_x, workspace[0]->Y + 180 * ratio_y),
				Point(workspace[0]->X + 816 * ratio_x, workspace[0]->Y + 181 * ratio_y),
				Point(workspace[0]->X + 819 * ratio_x, workspace[0]->Y + 182 * ratio_y),
				Point(workspace[0]->X + 820 * ratio_x, workspace[0]->Y + 183 * ratio_y),
				Point(workspace[0]->X + 820 * ratio_x, workspace[0]->Y + 181 * ratio_y),
				Point(workspace[0]->X + 820 * ratio_x, workspace[0]->Y + 178 * ratio_y),
				Point(workspace[0]->X + 820 * ratio_x, workspace[0]->Y + 177 * ratio_y),
				Point(workspace[0]->X + 822 * ratio_x, workspace[0]->Y + 177 * ratio_y),
				Point(workspace[0]->X + 823 * ratio_x, workspace[0]->Y + 177 * ratio_y),
				Point(workspace[0]->X + 825 * ratio_x, workspace[0]->Y + 179 * ratio_y),
				Point(workspace[0]->X + 825 * ratio_x, workspace[0]->Y + 180 * ratio_y),
				Point(workspace[0]->X + 826 * ratio_x, workspace[0]->Y + 181 * ratio_y),
				Point(workspace[0]->X + 827 * ratio_x, workspace[0]->Y + 183 * ratio_y),
				Point(workspace[0]->X + 828 * ratio_x, workspace[0]->Y + 184 * ratio_y),
				Point(workspace[0]->X + 830 * ratio_x, workspace[0]->Y + 185 * ratio_y),
				Point(workspace[0]->X + 831 * ratio_x, workspace[0]->Y + 185 * ratio_y),
				Point(workspace[0]->X + 833 * ratio_x, workspace[0]->Y + 185 * ratio_y),
				Point(workspace[0]->X + 834 * ratio_x, workspace[0]->Y + 184 * ratio_y),
				Point(workspace[0]->X + 836 * ratio_x, workspace[0]->Y + 184 * ratio_y),
				Point(workspace[0]->X + 837 * ratio_x, workspace[0]->Y + 185 * ratio_y),
				Point(workspace[0]->X + 838 * ratio_x, workspace[0]->Y + 185 * ratio_y),
				Point(workspace[0]->X + 839 * ratio_x, workspace[0]->Y + 187 * ratio_y),
				Point(workspace[0]->X + 838 * ratio_x, workspace[0]->Y + 189 * ratio_y),
				Point(workspace[0]->X + 836 * ratio_x, workspace[0]->Y + 190 * ratio_y),
				Point(workspace[0]->X + 836 * ratio_x, workspace[0]->Y + 194 * ratio_y),
				Point(workspace[0]->X + 838 * ratio_x, workspace[0]->Y + 195 * ratio_y),
				Point(workspace[0]->X + 839 * ratio_x, workspace[0]->Y + 197 * ratio_y),
				Point(workspace[0]->X + 841 * ratio_x, workspace[0]->Y + 199 * ratio_y),
				Point(workspace[0]->X + 843 * ratio_x, workspace[0]->Y + 200 * ratio_y),
				Point(workspace[0]->X + 845 * ratio_x, workspace[0]->Y + 201 * ratio_y),
				Point(workspace[0]->X + 847 * ratio_x, workspace[0]->Y + 200 * ratio_y),
				Point(workspace[0]->X + 848 * ratio_x, workspace[0]->Y + 200 * ratio_y),
				Point(workspace[0]->X + 849 * ratio_x, workspace[0]->Y + 201 * ratio_y),
				Point(workspace[0]->X + 850 * ratio_x, workspace[0]->Y + 202 * ratio_y),
				Point(workspace[0]->X + 852 * ratio_x, workspace[0]->Y + 204 * ratio_y),
				Point(workspace[0]->X + 850 * ratio_x, workspace[0]->Y + 205 * ratio_y),
				Point(workspace[0]->X + 849 * ratio_x, workspace[0]->Y + 206 * ratio_y),
				Point(workspace[0]->X + 846 * ratio_x, workspace[0]->Y + 208 * ratio_y),
				Point(workspace[0]->X + 846 * ratio_x, workspace[0]->Y + 210 * ratio_y),
				Point(workspace[0]->X + 846 * ratio_x, workspace[0]->Y + 212 * ratio_y),
				Point(workspace[0]->X + 847 * ratio_x, workspace[0]->Y + 216 * ratio_y),
				Point(workspace[0]->X + 848 * ratio_x, workspace[0]->Y + 217 * ratio_y),
				Point(workspace[0]->X + 849 * ratio_x, workspace[0]->Y + 219 * ratio_y),
				Point(workspace[0]->X + 850 * ratio_x, workspace[0]->Y + 220 * ratio_y),
				Point(workspace[0]->X + 851 * ratio_x, workspace[0]->Y + 221 * ratio_y),
				Point(workspace[0]->X + 854 * ratio_x, workspace[0]->Y + 222 * ratio_y),
				Point(workspace[0]->X + 856 * ratio_x, workspace[0]->Y + 223 * ratio_y),
				Point(workspace[0]->X + 854 * ratio_x, workspace[0]->Y + 225 * ratio_y),
				Point(workspace[0]->X + 854 * ratio_x, workspace[0]->Y + 228 * ratio_y),
				Point(workspace[0]->X + 854 * ratio_x, workspace[0]->Y + 230 * ratio_y),
				Point(workspace[0]->X + 854 * ratio_x, workspace[0]->Y + 233 * ratio_y),
				Point(workspace[0]->X + 856 * ratio_x, workspace[0]->Y + 235 * ratio_y),
				Point(workspace[0]->X + 857 * ratio_x, workspace[0]->Y + 236 * ratio_y),
				Point(workspace[0]->X + 858 * ratio_x, workspace[0]->Y + 238 * ratio_y),
				Point(workspace[0]->X + 860 * ratio_x, workspace[0]->Y + 240 * ratio_y),
				Point(workspace[0]->X + 862 * ratio_x, workspace[0]->Y + 241 * ratio_y),
				Point(workspace[0]->X + 863 * ratio_x, workspace[0]->Y + 242 * ratio_y),
				Point(workspace[0]->X + 864 * ratio_x, workspace[0]->Y + 248 * ratio_y),
				Point(workspace[0]->X + 865 * ratio_x, workspace[0]->Y + 255 * ratio_y),
				Point(workspace[0]->X + 864 * ratio_x, workspace[0]->Y + 256 * ratio_y),
				Point(workspace[0]->X + 861 * ratio_x, workspace[0]->Y + 255 * ratio_y),
				Point(workspace[0]->X + 859 * ratio_x, workspace[0]->Y + 254 * ratio_y),
				Point(workspace[0]->X + 856 * ratio_x, workspace[0]->Y + 253 * ratio_y),
				Point(workspace[0]->X + 855 * ratio_x, workspace[0]->Y + 252 * ratio_y),
				Point(workspace[0]->X + 852 * ratio_x, workspace[0]->Y + 251 * ratio_y),
				Point(workspace[0]->X + 849 * ratio_x, workspace[0]->Y + 248 * ratio_y),
				Point(workspace[0]->X + 847 * ratio_x, workspace[0]->Y + 247 * ratio_y),
				Point(workspace[0]->X + 843 * ratio_x, workspace[0]->Y + 246 * ratio_y),
				Point(workspace[0]->X + 840 * ratio_x, workspace[0]->Y + 245 * ratio_y),
				Point(workspace[0]->X + 839 * ratio_x, workspace[0]->Y + 244 * ratio_y),
				Point(workspace[0]->X + 837 * ratio_x, workspace[0]->Y + 244 * ratio_y),
				Point(workspace[0]->X + 835 * ratio_x, workspace[0]->Y + 242 * ratio_y),
				Point(workspace[0]->X + 834 * ratio_x, workspace[0]->Y + 241 * ratio_y),
				Point(workspace[0]->X + 831 * ratio_x, workspace[0]->Y + 239 * ratio_y),
				Point(workspace[0]->X + 829 * ratio_x, workspace[0]->Y + 239 * ratio_y),
				Point(workspace[0]->X + 826 * ratio_x, workspace[0]->Y + 238 * ratio_y),
				Point(workspace[0]->X + 824 * ratio_x, workspace[0]->Y + 237 * ratio_y),
				Point(workspace[0]->X + 822 * ratio_x, workspace[0]->Y + 236 * ratio_y),
				Point(workspace[0]->X + 819 * ratio_x, workspace[0]->Y + 234 * ratio_y),
				Point(workspace[0]->X + 818 * ratio_x, workspace[0]->Y + 233 * ratio_y),
				Point(workspace[0]->X + 815 * ratio_x, workspace[0]->Y + 231 * ratio_y),
				Point(workspace[0]->X + 814 * ratio_x, workspace[0]->Y + 229 * ratio_y),
				Point(workspace[0]->X + 812 * ratio_x, workspace[0]->Y + 227 * ratio_y),
				Point(workspace[0]->X + 810 * ratio_x, workspace[0]->Y + 224 * ratio_y),
				Point(workspace[0]->X + 808 * ratio_x, workspace[0]->Y + 221 * ratio_y),
				Point(workspace[0]->X + 807 * ratio_x, workspace[0]->Y + 219 * ratio_y),
				Point(workspace[0]->X + 807 * ratio_x, workspace[0]->Y + 217 * ratio_y),
				Point(workspace[0]->X + 806 * ratio_x, workspace[0]->Y + 215 * ratio_y),
				Point(workspace[0]->X + 805 * ratio_x, workspace[0]->Y + 214 * ratio_y),
				Point(workspace[0]->X + 804 * ratio_x, workspace[0]->Y + 212 * ratio_y),
				Point(workspace[0]->X + 802 * ratio_x, workspace[0]->Y + 211 * ratio_y),
				Point(workspace[0]->X + 801 * ratio_x, workspace[0]->Y + 211 * ratio_y),
				Point(workspace[0]->X + 803 * ratio_x, workspace[0]->Y + 210 * ratio_y),
				Point(workspace[0]->X + 804 * ratio_x, workspace[0]->Y + 207 * ratio_y),
				Point(workspace[0]->X + 803 * ratio_x, workspace[0]->Y + 205 * ratio_y),
				Point(workspace[0]->X + 804 * ratio_x, workspace[0]->Y + 202 * ratio_y),
				Point(workspace[0]->X + 803 * ratio_x, workspace[0]->Y + 200 * ratio_y),
				Point(workspace[0]->X + 801 * ratio_x, workspace[0]->Y + 188 * ratio_y),
				Point(workspace[0]->X + 799 * ratio_x, workspace[0]->Y + 186 * ratio_y),
				Point(workspace[0]->X + 793 * ratio_x, workspace[0]->Y + 167 * ratio_y),
				Point(workspace[0]->X + 791 * ratio_x, workspace[0]->Y + 165 * ratio_y),
				Point(workspace[0]->X + 792 * ratio_x, workspace[0]->Y + 164 * ratio_y),
				Point(workspace[0]->X + 792 * ratio_x, workspace[0]->Y + 161 * ratio_y),
				Point(workspace[0]->X + 792 * ratio_x, workspace[0]->Y + 159 * ratio_y),
				Point(workspace[0]->X + 792 * ratio_x, workspace[0]->Y + 158 * ratio_y),
				Point(workspace[0]->X + 792 * ratio_x, workspace[0]->Y + 157 * ratio_y),
				Point(workspace[0]->X + 791 * ratio_x, workspace[0]->Y + 155 * ratio_y),
				Point(workspace[0]->X + 790 * ratio_x, workspace[0]->Y + 154 * ratio_y),
				Point(workspace[0]->X + 788 * ratio_x, workspace[0]->Y + 152 * ratio_y),
				Point(workspace[0]->X + 785 * ratio_x, workspace[0]->Y + 150 * ratio_y),
				Point(workspace[0]->X + 784 * ratio_x, workspace[0]->Y + 149 * ratio_y),
				Point(workspace[0]->X + 783 * ratio_x, workspace[0]->Y + 148 * ratio_y),
				Point(workspace[0]->X + 782 * ratio_x, workspace[0]->Y + 146 * ratio_y),
				Point(workspace[0]->X + 780 * ratio_x, workspace[0]->Y + 145 * ratio_y),
				Point(workspace[0]->X + 779 * ratio_x, workspace[0]->Y + 144 * ratio_y),
				Point(workspace[0]->X + 779 * ratio_x, workspace[0]->Y + 143 * ratio_y),
				Point(workspace[0]->X + 781 * ratio_x, workspace[0]->Y + 141 * ratio_y),
				Point(workspace[0]->X + 781 * ratio_x, workspace[0]->Y + 138 * ratio_y),
				Point(workspace[0]->X + 779 * ratio_x, workspace[0]->Y + 138 * ratio_y),
				Point(workspace[0]->X + 778 * ratio_x, workspace[0]->Y + 140 * ratio_y),
				Point(workspace[0]->X + 776 * ratio_x, workspace[0]->Y + 141 * ratio_y),
				Point(workspace[0]->X + 775 * ratio_x, workspace[0]->Y + 142 * ratio_y),
				Point(workspace[0]->X + 775 * ratio_x, workspace[0]->Y + 145 * ratio_y),
				Point(workspace[0]->X + 774 * ratio_x, workspace[0]->Y + 147 * ratio_y),
				Point(workspace[0]->X + 777 * ratio_x, workspace[0]->Y + 151 * ratio_y),
				Point(workspace[0]->X + 780 * ratio_x, workspace[0]->Y + 153 * ratio_y),
				Point(workspace[0]->X + 782 * ratio_x, workspace[0]->Y + 155 * ratio_y),
				Point(workspace[0]->X + 781 * ratio_x, workspace[0]->Y + 156 * ratio_y),
				Point(workspace[0]->X + 781 * ratio_x, workspace[0]->Y + 159 * ratio_y),
				Point(workspace[0]->X + 781 * ratio_x, workspace[0]->Y + 161 * ratio_y),
				Point(workspace[0]->X + 782 * ratio_x, workspace[0]->Y + 165 * ratio_y),
				Point(workspace[0]->X + 783 * ratio_x, workspace[0]->Y + 167 * ratio_y),
				Point(workspace[0]->X + 783 * ratio_x, workspace[0]->Y + 170 * ratio_y),
				Point(workspace[0]->X + 783 * ratio_x, workspace[0]->Y + 172 * ratio_y),
				Point(workspace[0]->X + 781 * ratio_x, workspace[0]->Y + 171 * ratio_y),
				Point(workspace[0]->X + 778 * ratio_x, workspace[0]->Y + 172 * ratio_y),
				Point(workspace[0]->X + 776 * ratio_x, workspace[0]->Y + 171 * ratio_y),
				Point(workspace[0]->X + 775 * ratio_x, workspace[0]->Y + 168 * ratio_y),
				Point(workspace[0]->X + 773 * ratio_x, workspace[0]->Y + 165 * ratio_y),
				Point(workspace[0]->X + 771 * ratio_x, workspace[0]->Y + 165 * ratio_y),
				Point(workspace[0]->X + 772 * ratio_x, workspace[0]->Y + 171 * ratio_y),
				Point(workspace[0]->X + 769 * ratio_x, workspace[0]->Y + 171 * ratio_y),
				Point(workspace[0]->X + 767 * ratio_x, workspace[0]->Y + 172 * ratio_y),
				Point(workspace[0]->X + 766 * ratio_x, workspace[0]->Y + 177 * ratio_y),
				Point(workspace[0]->X + 765 * ratio_x, workspace[0]->Y + 178 * ratio_y),
				Point(workspace[0]->X + 765 * ratio_x, workspace[0]->Y + 180 * ratio_y),
				Point(workspace[0]->X + 764 * ratio_x, workspace[0]->Y + 182 * ratio_y),
				Point(workspace[0]->X + 764 * ratio_x, workspace[0]->Y + 185 * ratio_y),
				Point(workspace[0]->X + 765 * ratio_x, workspace[0]->Y + 186 * ratio_y),
				Point(workspace[0]->X + 766 * ratio_x, workspace[0]->Y + 189 * ratio_y),
				Point(workspace[0]->X + 766 * ratio_x, workspace[0]->Y + 191 * ratio_y),
				Point(workspace[0]->X + 767 * ratio_x, workspace[0]->Y + 193 * ratio_y),
				Point(workspace[0]->X + 769 * ratio_x, workspace[0]->Y + 196 * ratio_y),
				Point(workspace[0]->X + 769 * ratio_x, workspace[0]->Y + 199 * ratio_y),
				Point(workspace[0]->X + 769 * ratio_x, workspace[0]->Y + 200 * ratio_y),
				Point(workspace[0]->X + 769 * ratio_x, workspace[0]->Y + 202 * ratio_y),
				Point(workspace[0]->X + 769 * ratio_x, workspace[0]->Y + 205 * ratio_y),
				Point(workspace[0]->X + 771 * ratio_x, workspace[0]->Y + 207 * ratio_y),
				Point(workspace[0]->X + 772 * ratio_x, workspace[0]->Y + 210 * ratio_y),
				Point(workspace[0]->X + 774 * ratio_x, workspace[0]->Y + 212 * ratio_y),
				Point(workspace[0]->X + 776 * ratio_x, workspace[0]->Y + 209 * ratio_y),
				Point(workspace[0]->X + 778 * ratio_x, workspace[0]->Y + 209 * ratio_y),
				Point(workspace[0]->X + 779 * ratio_x, workspace[0]->Y + 209 * ratio_y),
				Point(workspace[0]->X + 778 * ratio_x, workspace[0]->Y + 211 * ratio_y),
				Point(workspace[0]->X + 778 * ratio_x, workspace[0]->Y + 212 * ratio_y),
				Point(workspace[0]->X + 777 * ratio_x, workspace[0]->Y + 215 * ratio_y),
				Point(workspace[0]->X + 775 * ratio_x, workspace[0]->Y + 215 * ratio_y),
				Point(workspace[0]->X + 774 * ratio_x, workspace[0]->Y + 215 * ratio_y),
				Point(workspace[0]->X + 774 * ratio_x, workspace[0]->Y + 218 * ratio_y),
				Point(workspace[0]->X + 773 * ratio_x, workspace[0]->Y + 222 * ratio_y),
				Point(workspace[0]->X + 772 * ratio_x, workspace[0]->Y + 222 * ratio_y),
				Point(workspace[0]->X + 771 * ratio_x, workspace[0]->Y + 225 * ratio_y),
				Point(workspace[0]->X + 771 * ratio_x, workspace[0]->Y + 227 * ratio_y),
				Point(workspace[0]->X + 770 * ratio_x, workspace[0]->Y + 229 * ratio_y),
				Point(workspace[0]->X + 768 * ratio_x, workspace[0]->Y + 228 * ratio_y),
				Point(workspace[0]->X + 769 * ratio_x, workspace[0]->Y + 225 * ratio_y),
				Point(workspace[0]->X + 769 * ratio_x, workspace[0]->Y + 222 * ratio_y),
				Point(workspace[0]->X + 767 * ratio_x, workspace[0]->Y + 224 * ratio_y),
				Point(workspace[0]->X + 765 * ratio_x, workspace[0]->Y + 224 * ratio_y),
				Point(workspace[0]->X + 762 * ratio_x, workspace[0]->Y + 225 * ratio_y),
				Point(workspace[0]->X + 761 * ratio_x, workspace[0]->Y + 226 * ratio_y),
				Point(workspace[0]->X + 758 * ratio_x, workspace[0]->Y + 228 * ratio_y),
				Point(workspace[0]->X + 757 * ratio_x, workspace[0]->Y + 229 * ratio_y),
				Point(workspace[0]->X + 755 * ratio_x, workspace[0]->Y + 230 * ratio_y),
				Point(workspace[0]->X + 754 * ratio_x, workspace[0]->Y + 231 * ratio_y),
				Point(workspace[0]->X + 753 * ratio_x, workspace[0]->Y + 232 * ratio_y),
				Point(workspace[0]->X + 753 * ratio_x, workspace[0]->Y + 235 * ratio_y),
				Point(workspace[0]->X + 753 * ratio_x, workspace[0]->Y + 236 * ratio_y),
				Point(workspace[0]->X + 754 * ratio_x, workspace[0]->Y + 238 * ratio_y),
				Point(workspace[0]->X + 754 * ratio_x, workspace[0]->Y + 239 * ratio_y),
				Point(workspace[0]->X + 751 * ratio_x, workspace[0]->Y + 239 * ratio_y),
				Point(workspace[0]->X + 750 * ratio_x, workspace[0]->Y + 241 * ratio_y),
				Point(workspace[0]->X + 749 * ratio_x, workspace[0]->Y + 244 * ratio_y),
				Point(workspace[0]->X + 747 * ratio_x, workspace[0]->Y + 245 * ratio_y),
				Point(workspace[0]->X + 745 * ratio_x, workspace[0]->Y + 246 * ratio_y),
				Point(workspace[0]->X + 744 * ratio_x, workspace[0]->Y + 247 * ratio_y),
				Point(workspace[0]->X + 744 * ratio_x, workspace[0]->Y + 249 * ratio_y),
				Point(workspace[0]->X + 744 * ratio_x, workspace[0]->Y + 251 * ratio_y),
				Point(workspace[0]->X + 742 * ratio_x, workspace[0]->Y + 251 * ratio_y),
				Point(workspace[0]->X + 741 * ratio_x, workspace[0]->Y + 251 * ratio_y),
				Point(workspace[0]->X + 738 * ratio_x, workspace[0]->Y + 253 * ratio_y),
				Point(workspace[0]->X + 734 * ratio_x, workspace[0]->Y + 258 * ratio_y),
				Point(workspace[0]->X + 730 * ratio_x, workspace[0]->Y + 263 * ratio_y),
				Point(workspace[0]->X + 728 * ratio_x, workspace[0]->Y + 267 * ratio_y),
				Point(workspace[0]->X + 727 * ratio_x, workspace[0]->Y + 270 * ratio_y),
				Point(workspace[0]->X + 727 * ratio_x, workspace[0]->Y + 272 * ratio_y),
				Point(workspace[0]->X + 728 * ratio_x, workspace[0]->Y + 274 * ratio_y),
				Point(workspace[0]->X + 730 * ratio_x, workspace[0]->Y + 275 * ratio_y),
				Point(workspace[0]->X + 728 * ratio_x, workspace[0]->Y + 278 * ratio_y),
				Point(workspace[0]->X + 727 * ratio_x, workspace[0]->Y + 281 * ratio_y),
				Point(workspace[0]->X + 727 * ratio_x, workspace[0]->Y + 281 * ratio_y),
				Point(workspace[0]->X + 727 * ratio_x, workspace[0]->Y + 285 * ratio_y),
				Point(workspace[0]->X + 728 * ratio_x, workspace[0]->Y + 287 * ratio_y),
				Point(workspace[0]->X + 729 * ratio_x, workspace[0]->Y + 289 * ratio_y),
				Point(workspace[0]->X + 728 * ratio_x, workspace[0]->Y + 292 * ratio_y),
				Point(workspace[0]->X + 729 * ratio_x, workspace[0]->Y + 294 * ratio_y),
				Point(workspace[0]->X + 728 * ratio_x, workspace[0]->Y + 298 * ratio_y),
				Point(workspace[0]->X + 728 * ratio_x, workspace[0]->Y + 301 * ratio_y),
				Point(workspace[0]->X + 728 * ratio_x, workspace[0]->Y + 304 * ratio_y),
				Point(workspace[0]->X + 727 * ratio_x, workspace[0]->Y + 309 * ratio_y),
				Point(workspace[0]->X + 729 * ratio_x, workspace[0]->Y + 310 * ratio_y),
				Point(workspace[0]->X + 729 * ratio_x, workspace[0]->Y + 313 * ratio_y),
				Point(workspace[0]->X + 729 * ratio_x, workspace[0]->Y + 315 * ratio_y),
				Point(workspace[0]->X + 729 * ratio_x, workspace[0]->Y + 318 * ratio_y),
				Point(workspace[0]->X + 729 * ratio_x, workspace[0]->Y + 321 * ratio_y),
				Point(workspace[0]->X + 728 * ratio_x, workspace[0]->Y + 326 * ratio_y),
				Point(workspace[0]->X + 726 * ratio_x, workspace[0]->Y + 328 * ratio_y),
				Point(workspace[0]->X + 726 * ratio_x, workspace[0]->Y + 331 * ratio_y),
				Point(workspace[0]->X + 725 * ratio_x, workspace[0]->Y + 333 * ratio_y),
				Point(workspace[0]->X + 725 * ratio_x, workspace[0]->Y + 335 * ratio_y),
				Point(workspace[0]->X + 726 * ratio_x, workspace[0]->Y + 338 * ratio_y),
				Point(workspace[0]->X + 729 * ratio_x, workspace[0]->Y + 338 * ratio_y),
				Point(workspace[0]->X + 732 * ratio_x, workspace[0]->Y + 337 * ratio_y),
				Point(workspace[0]->X + 733 * ratio_x, workspace[0]->Y + 336 * ratio_y),
				Point(workspace[0]->X + 736 * ratio_x, workspace[0]->Y + 333 * ratio_y),
				Point(workspace[0]->X + 737 * ratio_x, workspace[0]->Y + 334 * ratio_y),
				Point(workspace[0]->X + 738 * ratio_x, workspace[0]->Y + 336 * ratio_y),
				Point(workspace[0]->X + 739 * ratio_x, workspace[0]->Y + 338 * ratio_y),
				Point(workspace[0]->X + 741 * ratio_x, workspace[0]->Y + 340 * ratio_y),
				Point(workspace[0]->X + 742 * ratio_x, workspace[0]->Y + 340 * ratio_y),
				Point(workspace[0]->X + 744 * ratio_x, workspace[0]->Y + 339 * ratio_y),
				Point(workspace[0]->X + 744 * ratio_x, workspace[0]->Y + 338 * ratio_y),
				Point(workspace[0]->X + 743 * ratio_x, workspace[0]->Y + 335 * ratio_y),
				Point(workspace[0]->X + 742 * ratio_x, workspace[0]->Y + 334 * ratio_y),
				Point(workspace[0]->X + 744 * ratio_x, workspace[0]->Y + 334 * ratio_y),
				Point(workspace[0]->X + 746 * ratio_x, workspace[0]->Y + 337 * ratio_y),
				Point(workspace[0]->X + 746 * ratio_x, workspace[0]->Y + 338 * ratio_y),
				Point(workspace[0]->X + 746 * ratio_x, workspace[0]->Y + 340 * ratio_y),
				Point(workspace[0]->X + 748 * ratio_x, workspace[0]->Y + 339 * ratio_y),
				Point(workspace[0]->X + 749 * ratio_x, workspace[0]->Y + 338 * ratio_y),
				Point(workspace[0]->X + 750 * ratio_x, workspace[0]->Y + 336 * ratio_y),
				Point(workspace[0]->X + 752 * ratio_x, workspace[0]->Y + 335 * ratio_y),
				Point(workspace[0]->X + 754 * ratio_x, workspace[0]->Y + 335 * ratio_y),
				Point(workspace[0]->X + 755 * ratio_x, workspace[0]->Y + 335 * ratio_y),
				Point(workspace[0]->X + 753 * ratio_x, workspace[0]->Y + 332 * ratio_y),
				Point(workspace[0]->X + 751 * ratio_x, workspace[0]->Y + 329 * ratio_y),
				Point(workspace[0]->X + 750 * ratio_x, workspace[0]->Y + 327 * ratio_y),
				Point(workspace[0]->X + 750 * ratio_x, workspace[0]->Y + 295 * ratio_y),
				Point(workspace[1]->X, workspace[0]->Y + 295 * ratio_y),
			};
			array<Point>^ Russia1 = {
				Point(workspace[1]->X, workspace[0]->Y + 281 * ratio_y),
				Point(workspace[0]->X + 738 * ratio_x, workspace[0]->Y + 281 * ratio_y),
				Point(workspace[0]->X + 751 * ratio_x, workspace[0]->Y + 328 * ratio_y),
				Point(workspace[0]->X + 753 * ratio_x, workspace[0]->Y + 325 * ratio_y),
				Point(workspace[0]->X + 756 * ratio_x, workspace[0]->Y + 323 * ratio_y),
				Point(workspace[0]->X + 760 * ratio_x, workspace[0]->Y + 323 * ratio_y),
				Point(workspace[0]->X + 762 * ratio_x, workspace[0]->Y + 324 * ratio_y),
				Point(workspace[0]->X + 764 * ratio_x, workspace[0]->Y + 325 * ratio_y),
				Point(workspace[0]->X + 766 * ratio_x, workspace[0]->Y + 325 * ratio_y),
				Point(workspace[0]->X + 771 * ratio_x, workspace[0]->Y + 324 * ratio_y),
				Point(workspace[0]->X + 773 * ratio_x, workspace[0]->Y + 325 * ratio_y),
				Point(workspace[0]->X + 770 * ratio_x, workspace[0]->Y + 327 * ratio_y),
				Point(workspace[0]->X + 769 * ratio_x, workspace[0]->Y + 328 * ratio_y),
				Point(workspace[0]->X + 771 * ratio_x, workspace[0]->Y + 329 * ratio_y),
				Point(workspace[0]->X + 773 * ratio_x, workspace[0]->Y + 330 * ratio_y),
				Point(workspace[0]->X + 775 * ratio_x, workspace[0]->Y + 331 * ratio_y),
				Point(workspace[0]->X + 777 * ratio_x, workspace[0]->Y + 333 * ratio_y),
				Point(workspace[0]->X + 778 * ratio_x, workspace[0]->Y + 333 * ratio_y),
				Point(workspace[0]->X + 781 * ratio_x, workspace[0]->Y + 335 * ratio_y),
				Point(workspace[0]->X + 782 * ratio_x, workspace[0]->Y + 338 * ratio_y),
				Point(workspace[0]->X + 783 * ratio_x, workspace[0]->Y + 342 * ratio_y),
				Point(workspace[0]->X + 783 * ratio_x, workspace[0]->Y + 345 * ratio_y),
				Point(workspace[0]->X + 786 * ratio_x, workspace[0]->Y + 350 * ratio_y),
				Point(workspace[0]->X + 788 * ratio_x, workspace[0]->Y + 353 * ratio_y),
				Point(workspace[0]->X + 791 * ratio_x, workspace[0]->Y + 356 * ratio_y),
				Point(workspace[0]->X + 794 * ratio_x, workspace[0]->Y + 359 * ratio_y),
				Point(workspace[0]->X + 796 * ratio_x, workspace[0]->Y + 363 * ratio_y),
				Point(workspace[0]->X + 798 * ratio_x, workspace[0]->Y + 366 * ratio_y),
				Point(workspace[0]->X + 801 * ratio_x, workspace[0]->Y + 371 * ratio_y),
				Point(workspace[0]->X + 803 * ratio_x, workspace[0]->Y + 373 * ratio_y),
				Point(workspace[0]->X + 802 * ratio_x, workspace[0]->Y + 375 * ratio_y),
				Point(workspace[0]->X + 802 * ratio_x, workspace[0]->Y + 381 * ratio_y),
				Point(workspace[0]->X + 802 * ratio_x, workspace[0]->Y + 384 * ratio_y),
				Point(workspace[0]->X + 803 * ratio_x, workspace[0]->Y + 388 * ratio_y),
				Point(workspace[0]->X + 803 * ratio_x, workspace[0]->Y + 392 * ratio_y),
				Point(workspace[0]->X + 804 * ratio_x, workspace[0]->Y + 395 * ratio_y),
				Point(workspace[0]->X + 806 * ratio_x, workspace[0]->Y + 402 * ratio_y),
				Point(workspace[0]->X + 807 * ratio_x, workspace[0]->Y + 407 * ratio_y),
				Point(workspace[0]->X + 808 * ratio_x, workspace[0]->Y + 413 * ratio_y),
				Point(workspace[0]->X + 807 * ratio_x, workspace[0]->Y + 418 * ratio_y),
				Point(workspace[0]->X + 806 * ratio_x, workspace[0]->Y + 423 * ratio_y),
				Point(workspace[0]->X + 806 * ratio_x, workspace[0]->Y + 451 * ratio_y),
				Point(workspace[0]->X + 800 * ratio_x, workspace[0]->Y + 462 * ratio_y),
				Point(workspace[0]->X + 797 * ratio_x, workspace[0]->Y + 463 * ratio_y),
				Point(workspace[0]->X + 795 * ratio_x, workspace[0]->Y + 463 * ratio_y),
				Point(workspace[0]->X + 790 * ratio_x, workspace[0]->Y + 464 * ratio_y),
				Point(workspace[0]->X + 869 * ratio_x, workspace[0]->Y + 477 * ratio_y),
				Point(workspace[0]->X + 834 * ratio_x, workspace[0]->Y + 384 * ratio_y),
				Point(workspace[0]->X + 826 * ratio_x, workspace[0]->Y + 378 * ratio_y),
				Point(workspace[0]->X + 825 * ratio_x, workspace[0]->Y + 376 * ratio_y),
				Point(workspace[0]->X + 823 * ratio_x, workspace[0]->Y + 373 * ratio_y),
				Point(workspace[0]->X + 821 * ratio_x, workspace[0]->Y + 371 * ratio_y),
				Point(workspace[0]->X + 819 * ratio_x, workspace[0]->Y + 368 * ratio_y),
				Point(workspace[0]->X + 817 * ratio_x, workspace[0]->Y + 366 * ratio_y),
				Point(workspace[0]->X + 815 * ratio_x, workspace[0]->Y + 364 * ratio_y),
				Point(workspace[0]->X + 812 * ratio_x, workspace[0]->Y + 362 * ratio_y),
				Point(workspace[0]->X + 810 * ratio_x, workspace[0]->Y + 361 * ratio_y),
				Point(workspace[0]->X + 808 * ratio_x, workspace[0]->Y + 357 * ratio_y),
				Point(workspace[0]->X + 806 * ratio_x, workspace[0]->Y + 353 * ratio_y),
				Point(workspace[0]->X + 803 * ratio_x, workspace[0]->Y + 349 * ratio_y),
				Point(workspace[0]->X + 801 * ratio_x, workspace[0]->Y + 346 * ratio_y),
				Point(workspace[0]->X + 798 * ratio_x, workspace[0]->Y + 343 * ratio_y),
				Point(workspace[0]->X + 796 * ratio_x, workspace[0]->Y + 342 * ratio_y),
				Point(workspace[0]->X + 795 * ratio_x, workspace[0]->Y + 341 * ratio_y),
				Point(workspace[0]->X + 794 * ratio_x, workspace[0]->Y + 340 * ratio_y),
				Point(workspace[0]->X + 794 * ratio_x, workspace[0]->Y + 339 * ratio_y),
				Point(workspace[0]->X + 793 * ratio_x, workspace[0]->Y + 337 * ratio_y),
				Point(workspace[0]->X + 790 * ratio_x, workspace[0]->Y + 335 * ratio_y),
				Point(workspace[0]->X + 788 * ratio_x, workspace[0]->Y + 335 * ratio_y),
				Point(workspace[0]->X + 785 * ratio_x, workspace[0]->Y + 333 * ratio_y),
				Point(workspace[0]->X + 782 * ratio_x, workspace[0]->Y + 332 * ratio_y),
				Point(workspace[0]->X + 780 * ratio_x, workspace[0]->Y + 331 * ratio_y),
				Point(workspace[0]->X + 779 * ratio_x, workspace[0]->Y + 328 * ratio_y),
				Point(workspace[0]->X + 778 * ratio_x, workspace[0]->Y + 325 * ratio_y),
				Point(workspace[0]->X + 777 * ratio_x, workspace[0]->Y + 324 * ratio_y),
				Point(workspace[0]->X + 776 * ratio_x, workspace[0]->Y + 322 * ratio_y),
				Point(workspace[0]->X + 774 * ratio_x, workspace[0]->Y + 321 * ratio_y),
				Point(workspace[0]->X + 773 * ratio_x, workspace[0]->Y + 321 * ratio_y),
				Point(workspace[0]->X + 773 * ratio_x, workspace[0]->Y + 319 * ratio_y),
				Point(workspace[0]->X + 775 * ratio_x, workspace[0]->Y + 319 * ratio_y),
				Point(workspace[0]->X + 775 * ratio_x, workspace[0]->Y + 318 * ratio_y),
				Point(workspace[0]->X + 775 * ratio_x, workspace[0]->Y + 314 * ratio_y),
				Point(workspace[0]->X + 773 * ratio_x, workspace[0]->Y + 312 * ratio_y),
				Point(workspace[0]->X + 769 * ratio_x, workspace[0]->Y + 309 * ratio_y),
				Point(workspace[0]->X + 770 * ratio_x, workspace[0]->Y + 309 * ratio_y),
				Point(workspace[0]->X + 773 * ratio_x, workspace[0]->Y + 310 * ratio_y),
				Point(workspace[0]->X + 777 * ratio_x, workspace[0]->Y + 313 * ratio_y),
				Point(workspace[0]->X + 780 * ratio_x, workspace[0]->Y + 316 * ratio_y),
				Point(workspace[0]->X + 783 * ratio_x, workspace[0]->Y + 318 * ratio_y),
				Point(workspace[0]->X + 785 * ratio_x, workspace[0]->Y + 318 * ratio_y),
				Point(workspace[0]->X + 787 * ratio_x, workspace[0]->Y + 322 * ratio_y),
				Point(workspace[0]->X + 788 * ratio_x, workspace[0]->Y + 324 * ratio_y),
				Point(workspace[0]->X + 792 * ratio_x, workspace[0]->Y + 327 * ratio_y),
				Point(workspace[0]->X + 794 * ratio_x, workspace[0]->Y + 329 * ratio_y),
				Point(workspace[0]->X + 797 * ratio_x, workspace[0]->Y + 331 * ratio_y),
				Point(workspace[0]->X + 800 * ratio_x, workspace[0]->Y + 332 * ratio_y),
				Point(workspace[0]->X + 802 * ratio_x, workspace[0]->Y + 334 * ratio_y),
				Point(workspace[0]->X + 805 * ratio_x, workspace[0]->Y + 335 * ratio_y),
				Point(workspace[0]->X + 808 * ratio_x, workspace[0]->Y + 337 * ratio_y),
				Point(workspace[0]->X + 809 * ratio_x, workspace[0]->Y + 339 * ratio_y),
				Point(workspace[0]->X + 812 * ratio_x, workspace[0]->Y + 340 * ratio_y),
				Point(workspace[0]->X + 814 * ratio_x, workspace[0]->Y + 342 * ratio_y),
				Point(workspace[0]->X + 816 * ratio_x, workspace[0]->Y + 343 * ratio_y),
				Point(workspace[0]->X + 819 * ratio_x, workspace[0]->Y + 343 * ratio_y),
				Point(workspace[0]->X + 818 * ratio_x, workspace[0]->Y + 345 * ratio_y),
				Point(workspace[0]->X + 815 * ratio_x, workspace[0]->Y + 345 * ratio_y),
				Point(workspace[0]->X + 813 * ratio_x, workspace[0]->Y + 346 * ratio_y),
				Point(workspace[0]->X + 812 * ratio_x, workspace[0]->Y + 350 * ratio_y),
				Point(workspace[0]->X + 813 * ratio_x, workspace[0]->Y + 353 * ratio_y),
				Point(workspace[0]->X + 814 * ratio_x, workspace[0]->Y + 355 * ratio_y),
				Point(workspace[0]->X + 816 * ratio_x, workspace[0]->Y + 356 * ratio_y),
				Point(workspace[0]->X + 817 * ratio_x, workspace[0]->Y + 357 * ratio_y),
				Point(workspace[0]->X + 817 * ratio_x, workspace[0]->Y + 361 * ratio_y),
				Point(workspace[0]->X + 822 * ratio_x, workspace[0]->Y + 365 * ratio_y),
				Point(workspace[0]->X + 825 * ratio_x, workspace[0]->Y + 367 * ratio_y),
				Point(workspace[0]->X + 829 * ratio_x, workspace[0]->Y + 369 * ratio_y),
				Point(workspace[0]->X + 830 * ratio_x, workspace[0]->Y + 370 * ratio_y),
				Point(workspace[0]->X + 833 * ratio_x, workspace[0]->Y + 370 * ratio_y),
				Point(workspace[0]->X + 838 * ratio_x, workspace[0]->Y + 370 * ratio_y),
				Point(workspace[0]->X + 840 * ratio_x, workspace[0]->Y + 373 * ratio_y),
				Point(workspace[0]->X + 838 * ratio_x, workspace[0]->Y + 373 * ratio_y),
				Point(workspace[0]->X + 836 * ratio_x, workspace[0]->Y + 373 * ratio_y),
				Point(workspace[0]->X + 832 * ratio_x, workspace[0]->Y + 373 * ratio_y),
				Point(workspace[0]->X + 830 * ratio_x, workspace[0]->Y + 375 * ratio_y),
				Point(workspace[0]->X + 830 * ratio_x, workspace[0]->Y + 377 * ratio_y),
				Point(workspace[0]->X + 832 * ratio_x, workspace[0]->Y + 380 * ratio_y),
				Point(workspace[0]->X + 833 * ratio_x, workspace[0]->Y + 382 * ratio_y),
				Point(workspace[0]->X + 834 * ratio_x, workspace[0]->Y + 385 * ratio_y),
				Point(workspace[1]->X, workspace[0]->Y + 385 * ratio_y),
			};
			array<Point>^ Russia2 = {
				Point(workspace[1]->X, workspace[0]->Y + 385 * ratio_y),
				Point(workspace[0]->X + 834 * ratio_x, workspace[0]->Y + 385 * ratio_y),
				Point(workspace[0]->X + 830 * ratio_x, workspace[0]->Y + 462 * ratio_y),
				Point(workspace[0]->X + 792 * ratio_x, workspace[0]->Y + 464 * ratio_y),
				Point(workspace[0]->X + 792 * ratio_x, workspace[1]->Y),
				Point(workspace[1]->X, workspace[1]->Y)
			};
			array<Point>^ Russia3 = {
				Point(workspace[0]->X + 792 * ratio_x, workspace[1]->Y),
				Point(workspace[0]->X + 792 * ratio_x, workspace[0]->Y + 464 * ratio_y),
				Point(workspace[0]->X + 789 * ratio_x, workspace[0]->Y + 460 * ratio_y),
				Point(workspace[0]->X + 787 * ratio_x, workspace[0]->Y + 463 * ratio_y),
				Point(workspace[0]->X + 785 * ratio_x, workspace[0]->Y + 462 * ratio_y),
				Point(workspace[0]->X + 784 * ratio_x, workspace[0]->Y + 471 * ratio_y),
				Point(workspace[0]->X + 780 * ratio_x, workspace[0]->Y + 477 * ratio_y),
				Point(workspace[0]->X + 780 * ratio_x, workspace[0]->Y + 476 * ratio_y),
				Point(workspace[0]->X + 781 * ratio_x, workspace[0]->Y + 469 * ratio_y),
				Point(workspace[0]->X + 781 * ratio_x, workspace[0]->Y + 463 * ratio_y),
				Point(workspace[0]->X + 777 * ratio_x, workspace[0]->Y + 460 * ratio_y),
				Point(workspace[0]->X + 775 * ratio_x, workspace[0]->Y + 455 * ratio_y),
				Point(workspace[0]->X + 771 * ratio_x, workspace[0]->Y + 453 * ratio_y),
				Point(workspace[0]->X + 770 * ratio_x, workspace[0]->Y + 450 * ratio_y),
				Point(workspace[0]->X + 772 * ratio_x, workspace[0]->Y + 448 * ratio_y),
				Point(workspace[0]->X + 773 * ratio_x, workspace[0]->Y + 445 * ratio_y),
				Point(workspace[0]->X + 776 * ratio_x, workspace[0]->Y + 442 * ratio_y),
				Point(workspace[0]->X + 779 * ratio_x, workspace[0]->Y + 443 * ratio_y),
				Point(workspace[0]->X + 783 * ratio_x, workspace[0]->Y + 438 * ratio_y),
				Point(workspace[0]->X + 781 * ratio_x, workspace[0]->Y + 435 * ratio_y),
				Point(workspace[0]->X + 781 * ratio_x, workspace[0]->Y + 434 * ratio_y),
				Point(workspace[0]->X + 782 * ratio_x, workspace[0]->Y + 432 * ratio_y),
				Point(workspace[0]->X + 780 * ratio_x, workspace[0]->Y + 428 * ratio_y),
				Point(workspace[0]->X + 780 * ratio_x, workspace[0]->Y + 426 * ratio_y),
				Point(workspace[0]->X + 779 * ratio_x, workspace[0]->Y + 424 * ratio_y),
				Point(workspace[0]->X + 776 * ratio_x, workspace[0]->Y + 417 * ratio_y),
				Point(workspace[0]->X + 774 * ratio_x, workspace[0]->Y + 413 * ratio_y),
				Point(workspace[0]->X + 776 * ratio_x, workspace[0]->Y + 409 * ratio_y),
				Point(workspace[0]->X + 775 * ratio_x, workspace[0]->Y + 407 * ratio_y),
				Point(workspace[0]->X + 771 * ratio_x, workspace[0]->Y + 403 * ratio_y),
				Point(workspace[0]->X + 771 * ratio_x, workspace[0]->Y + 401 * ratio_y),
				Point(workspace[0]->X + 765 * ratio_x, workspace[0]->Y + 402 * ratio_y),
				Point(workspace[0]->X + 760 * ratio_x, workspace[0]->Y + 411 * ratio_y),
				Point(workspace[0]->X + 760 * ratio_x, workspace[0]->Y + 416 * ratio_y),
				Point(workspace[0]->X + 752 * ratio_x, workspace[0]->Y + 420 * ratio_y),
				Point(workspace[0]->X + 751 * ratio_x, workspace[0]->Y + 422 * ratio_y),
				Point(workspace[0]->X + 746 * ratio_x, workspace[0]->Y + 420 * ratio_y),
				Point(workspace[0]->X + 745 * ratio_x, workspace[0]->Y + 416 * ratio_y),
				Point(workspace[0]->X + 740 * ratio_x, workspace[0]->Y + 413 * ratio_y),
				Point(workspace[0]->X + 736 * ratio_x, workspace[0]->Y + 414 * ratio_y),
				Point(workspace[0]->X + 730 * ratio_x, workspace[0]->Y + 413 * ratio_y),
				Point(workspace[0]->X + 724 * ratio_x, workspace[0]->Y + 414 * ratio_y),
				Point(workspace[0]->X + 721 * ratio_x, workspace[0]->Y + 416 * ratio_y),
				Point(workspace[0]->X + 713 * ratio_x, workspace[0]->Y + 415 * ratio_y),
				Point(workspace[0]->X + 705 * ratio_x, workspace[0]->Y + 405 * ratio_y),
				Point(workspace[0]->X + 702 * ratio_x, workspace[0]->Y + 406 * ratio_y),
				Point(workspace[0]->X + 700 * ratio_x, workspace[0]->Y + 402 * ratio_y),
				Point(workspace[0]->X + 694 * ratio_x, workspace[0]->Y + 397 * ratio_y),
				Point(workspace[0]->X + 692 * ratio_x, workspace[0]->Y + 397 * ratio_y),
				Point(workspace[0]->X + 691 * ratio_x, workspace[0]->Y + 393 * ratio_y),
				Point(workspace[0]->X + 688 * ratio_x, workspace[0]->Y + 392 * ratio_y),
				Point(workspace[0]->X + 685 * ratio_x, workspace[0]->Y + 391 * ratio_y),
				Point(workspace[0]->X + 681 * ratio_x, workspace[0]->Y + 390 * ratio_y),
				Point(workspace[0]->X + 679 * ratio_x, workspace[0]->Y + 390 * ratio_y),
				Point(workspace[0]->X + 674 * ratio_x, workspace[0]->Y + 391 * ratio_y),
				Point(workspace[0]->X + 669 * ratio_x, workspace[0]->Y + 391 * ratio_y),
				Point(workspace[0]->X + 663 * ratio_x, workspace[0]->Y + 393 * ratio_y),
				Point(workspace[0]->X + 657 * ratio_x, workspace[0]->Y + 398 * ratio_y),
				Point(workspace[0]->X + 651 * ratio_x, workspace[0]->Y + 401 * ratio_y),
				Point(workspace[0]->X + 647 * ratio_x, workspace[0]->Y + 411 * ratio_y),
				Point(workspace[0]->X + 649 * ratio_x, workspace[0]->Y + 412 * ratio_y),
				Point(workspace[0]->X + 651 * ratio_x, workspace[0]->Y + 411 * ratio_y),
				Point(workspace[0]->X + 655 * ratio_x, workspace[0]->Y + 415 * ratio_y),
				Point(workspace[0]->X + 656 * ratio_x, workspace[0]->Y + 418 * ratio_y),
				Point(workspace[0]->X + 654 * ratio_x, workspace[0]->Y + 424 * ratio_y),
				Point(workspace[0]->X + 654 * ratio_x, workspace[0]->Y + 428 * ratio_y),
				Point(workspace[0]->X + 653 * ratio_x, workspace[0]->Y + 430 * ratio_y),
				Point(workspace[0]->X + 652 * ratio_x, workspace[0]->Y + 434 * ratio_y),
				Point(workspace[0]->X + 655 * ratio_x, workspace[0]->Y + 439 * ratio_y),
				Point(workspace[0]->X + 655 * ratio_x, workspace[0]->Y + 443 * ratio_y),
				Point(workspace[0]->X + 652 * ratio_x, workspace[0]->Y + 443 * ratio_y),
				Point(workspace[0]->X + 649 * ratio_x, workspace[0]->Y + 450 * ratio_y),
				Point(workspace[0]->X + 647 * ratio_x, workspace[0]->Y + 451 * ratio_y),
				Point(workspace[0]->X + 644 * ratio_x, workspace[0]->Y + 452 * ratio_y),
				Point(workspace[0]->X + 639 * ratio_x, workspace[0]->Y + 452 * ratio_y),
				Point(workspace[0]->X + 635 * ratio_x, workspace[0]->Y + 451 * ratio_y),
				Point(workspace[0]->X + 629 * ratio_x, workspace[0]->Y + 455 * ratio_y),
				Point(workspace[0]->X + 626 * ratio_x, workspace[0]->Y + 453 * ratio_y),
				Point(workspace[0]->X + 622 * ratio_x, workspace[0]->Y + 453 * ratio_y),
				Point(workspace[0]->X + 619 * ratio_x, workspace[0]->Y + 454 * ratio_y),
				Point(workspace[0]->X + 616 * ratio_x, workspace[0]->Y + 458 * ratio_y),
				Point(workspace[0]->X + 614 * ratio_x, workspace[0]->Y + 459 * ratio_y),
				Point(workspace[0]->X + 613 * ratio_x, workspace[0]->Y + 462 * ratio_y),
				Point(workspace[0]->X + 611 * ratio_x, workspace[0]->Y + 465 * ratio_y),
				Point(workspace[0]->X + 609 * ratio_x, workspace[0]->Y + 467 * ratio_y),
				Point(workspace[0]->X + 606 * ratio_x, workspace[0]->Y + 469 * ratio_y),
				Point(workspace[0]->X + 603 * ratio_x, workspace[0]->Y + 469 * ratio_y),
				Point(workspace[0]->X + 601 * ratio_x, workspace[0]->Y + 472 * ratio_y),
				Point(workspace[0]->X + 598 * ratio_x, workspace[0]->Y + 474 * ratio_y),
				Point(workspace[0]->X + 595 * ratio_x, workspace[0]->Y + 474 * ratio_y),
				Point(workspace[0]->X + 592 * ratio_x, workspace[0]->Y + 475 * ratio_y),
				Point(workspace[0]->X + 590 * ratio_x, workspace[0]->Y + 475 * ratio_y),
				Point(workspace[0]->X + 588 * ratio_x, workspace[0]->Y + 476 * ratio_y),
				Point(workspace[0]->X + 583 * ratio_x, workspace[0]->Y + 476 * ratio_y),
				Point(workspace[0]->X + 579 * ratio_x, workspace[0]->Y + 476 * ratio_y),
				Point(workspace[0]->X + 578 * ratio_x, workspace[0]->Y + 476 * ratio_y),
				Point(workspace[0]->X + 575 * ratio_x, workspace[0]->Y + 473 * ratio_y),
				Point(workspace[0]->X + 574 * ratio_x, workspace[0]->Y + 471 * ratio_y),
				Point(workspace[0]->X + 570 * ratio_x, workspace[0]->Y + 472 * ratio_y),
				Point(workspace[0]->X + 567 * ratio_x, workspace[0]->Y + 472 * ratio_y),
				Point(workspace[0]->X + 566 * ratio_x, workspace[0]->Y + 471 * ratio_y),
				Point(workspace[0]->X + 562 * ratio_x, workspace[0]->Y + 470 * ratio_y),
				Point(workspace[0]->X + 560 * ratio_x, workspace[0]->Y + 470 * ratio_y),
				Point(workspace[0]->X + 555 * ratio_x, workspace[0]->Y + 471 * ratio_y),
				Point(workspace[0]->X + 553 * ratio_x, workspace[0]->Y + 471 * ratio_y),
				Point(workspace[0]->X + 552 * ratio_x, workspace[0]->Y + 471 * ratio_y),
				Point(workspace[0]->X + 550 * ratio_x, workspace[0]->Y + 472 * ratio_y),
				Point(workspace[0]->X + 548 * ratio_x, workspace[0]->Y + 474 * ratio_y),
				Point(workspace[0]->X + 545 * ratio_x, workspace[0]->Y + 474 * ratio_y),
				Point(workspace[0]->X + 541 * ratio_x, workspace[0]->Y + 475 * ratio_y),
				Point(workspace[0]->X + 541 * ratio_x, workspace[0]->Y + 475 * ratio_y),
				Point(workspace[0]->X + 538 * ratio_x, workspace[0]->Y + 475 * ratio_y),
				Point(workspace[0]->X + 535 * ratio_x, workspace[0]->Y + 475 * ratio_y),
				Point(workspace[0]->X + 532 * ratio_x, workspace[0]->Y + 473 * ratio_y),
				Point(workspace[0]->X + 531 * ratio_x, workspace[0]->Y + 470 * ratio_y),
				Point(workspace[0]->X + 528 * ratio_x, workspace[0]->Y + 466 * ratio_y),
				Point(workspace[0]->X + 526 * ratio_x, workspace[0]->Y + 465 * ratio_y),
				Point(workspace[0]->X + 525 * ratio_x, workspace[0]->Y + 464 * ratio_y),
				Point(workspace[0]->X + 522 * ratio_x, workspace[0]->Y + 463 * ratio_y),
				Point(workspace[0]->X + 516 * ratio_x, workspace[0]->Y + 464 * ratio_y),
				Point(workspace[0]->X + 515 * ratio_x, workspace[0]->Y + 464 * ratio_y),
				Point(workspace[0]->X + 512 * ratio_x, workspace[0]->Y + 461 * ratio_y),
				Point(workspace[0]->X + 507 * ratio_x, workspace[0]->Y + 461 * ratio_y),
				Point(workspace[0]->X + 504 * ratio_x, workspace[0]->Y + 460 * ratio_y),
				Point(workspace[0]->X + 501 * ratio_x, workspace[0]->Y + 463 * ratio_y),
				Point(workspace[0]->X + 499 * ratio_x, workspace[0]->Y + 464 * ratio_y),
				Point(workspace[0]->X + 497 * ratio_x, workspace[0]->Y + 468 * ratio_y),
				Point(workspace[0]->X + 496 * ratio_x, workspace[0]->Y + 471 * ratio_y),
				Point(workspace[0]->X + 497 * ratio_x, workspace[0]->Y + 476 * ratio_y),
				Point(workspace[0]->X + 500 * ratio_x, workspace[0]->Y + 480 * ratio_y),
				Point(workspace[0]->X + 501 * ratio_x, workspace[0]->Y + 482 * ratio_y),
				Point(workspace[0]->X + 498 * ratio_x, workspace[0]->Y + 484 * ratio_y),
				Point(workspace[0]->X + 493 * ratio_x, workspace[0]->Y + 487 * ratio_y),
				Point(workspace[0]->X + 488 * ratio_x, workspace[0]->Y + 487 * ratio_y),
				Point(workspace[0]->X + 483 * ratio_x, workspace[0]->Y + 488 * ratio_y),
				Point(workspace[0]->X + 479 * ratio_x, workspace[0]->Y + 488 * ratio_y),
				Point(workspace[0]->X + 476 * ratio_x, workspace[0]->Y + 487 * ratio_y),
				Point(workspace[0]->X + 474 * ratio_x, workspace[0]->Y + 485 * ratio_y),
				Point(workspace[0]->X + 472 * ratio_x, workspace[0]->Y + 483 * ratio_y),
				Point(workspace[0]->X + 469 * ratio_x, workspace[0]->Y + 480 * ratio_y),
				Point(workspace[0]->X + 467 * ratio_x, workspace[0]->Y + 480 * ratio_y),
				Point(workspace[0]->X + 465 * ratio_x, workspace[0]->Y + 480 * ratio_y),
				Point(workspace[0]->X + 463 * ratio_x, workspace[0]->Y + 481 * ratio_y),
				Point(workspace[0]->X + 460 * ratio_x, workspace[0]->Y + 479 * ratio_y),
				Point(workspace[0]->X + 457 * ratio_x, workspace[0]->Y + 479 * ratio_y),
				Point(workspace[0]->X + 455 * ratio_x, workspace[0]->Y + 479 * ratio_y),
				Point(workspace[0]->X + 453 * ratio_x, workspace[0]->Y + 480 * ratio_y),
				Point(workspace[0]->X + 451 * ratio_x, workspace[0]->Y + 481 * ratio_y),
				Point(workspace[0]->X + 450 * ratio_x, workspace[0]->Y + 482 * ratio_y),
				Point(workspace[0]->X + 447 * ratio_x, workspace[0]->Y + 483 * ratio_y),
				Point(workspace[0]->X + 444 * ratio_x, workspace[0]->Y + 485 * ratio_y),
				Point(workspace[0]->X + 442 * ratio_x, workspace[0]->Y + 486 * ratio_y),
				Point(workspace[0]->X + 438 * ratio_x, workspace[0]->Y + 488 * ratio_y),
				Point(workspace[0]->X + 436 * ratio_x, workspace[0]->Y + 488 * ratio_y),
				Point(workspace[0]->X + 435 * ratio_x, workspace[0]->Y + 491 * ratio_y),
				Point(workspace[0]->X + 432 * ratio_x, workspace[0]->Y + 492 * ratio_y),
				Point(workspace[0]->X + 429 * ratio_x, workspace[0]->Y + 494 * ratio_y),
				Point(workspace[0]->X + 426 * ratio_x, workspace[0]->Y + 494 * ratio_y),
				Point(workspace[0]->X + 423 * ratio_x, workspace[0]->Y + 496 * ratio_y),
				Point(workspace[0]->X + 420 * ratio_x, workspace[0]->Y + 498 * ratio_y),
				Point(workspace[0]->X + 417 * ratio_x, workspace[0]->Y + 497 * ratio_y),
				Point(workspace[0]->X + 416 * ratio_x, workspace[0]->Y + 494 * ratio_y),
				Point(workspace[0]->X + 414 * ratio_x, workspace[0]->Y + 491 * ratio_y),
				Point(workspace[0]->X + 412 * ratio_x, workspace[0]->Y + 492 * ratio_y),
				Point(workspace[0]->X + 410 * ratio_x, workspace[0]->Y + 492 * ratio_y),
				Point(workspace[0]->X + 407 * ratio_x, workspace[0]->Y + 493 * ratio_y),
				Point(workspace[0]->X + 404 * ratio_x, workspace[0]->Y + 492 * ratio_y),
				Point(workspace[0]->X + 401 * ratio_x, workspace[0]->Y + 490 * ratio_y),
				Point(workspace[0]->X + 401 * ratio_x, workspace[0]->Y + 489 * ratio_y),
				Point(workspace[0]->X + 398 * ratio_x, workspace[0]->Y + 486 * ratio_y),
				Point(workspace[0]->X + 396 * ratio_x, workspace[0]->Y + 483 * ratio_y),
				Point(workspace[0]->X + 395 * ratio_x, workspace[0]->Y + 482 * ratio_y),
				Point(workspace[0]->X + 395 * ratio_x, workspace[0]->Y + 479 * ratio_y),
				Point(workspace[0]->X + 393 * ratio_x, workspace[0]->Y + 478 * ratio_y),
				Point(workspace[0]->X + 391 * ratio_x, workspace[0]->Y + 477 * ratio_y),
				Point(workspace[0]->X + 388 * ratio_x, workspace[0]->Y + 474 * ratio_y),
				Point(workspace[0]->X + 386 * ratio_x, workspace[0]->Y + 474 * ratio_y),
				Point(workspace[0]->X + 384 * ratio_x, workspace[0]->Y + 474 * ratio_y),
				Point(workspace[0]->X + 382 * ratio_x, workspace[0]->Y + 476 * ratio_y),
				Point(workspace[0]->X + 380 * ratio_x, workspace[0]->Y + 476 * ratio_y),
				Point(workspace[0]->X + 378 * ratio_x, workspace[0]->Y + 476 * ratio_y),
				Point(workspace[0]->X + 374 * ratio_x, workspace[0]->Y + 475 * ratio_y),
				Point(workspace[0]->X + 372 * ratio_x, workspace[0]->Y + 474 * ratio_y),
				Point(workspace[0]->X + 372 * ratio_x, workspace[0]->Y + 472 * ratio_y),
				Point(workspace[0]->X + 370 * ratio_x, workspace[0]->Y + 470 * ratio_y),
				Point(workspace[0]->X + 369 * ratio_x, workspace[0]->Y + 470 * ratio_y),
				Point(workspace[0]->X + 367 * ratio_x, workspace[0]->Y + 470 * ratio_y),
				Point(workspace[0]->X + 366 * ratio_x, workspace[0]->Y + 472 * ratio_y),
				Point(workspace[0]->X + 365 * ratio_x, workspace[0]->Y + 473 * ratio_y),
				Point(workspace[0]->X + 363 * ratio_x, workspace[0]->Y + 472 * ratio_y),
				Point(workspace[0]->X + 362 * ratio_x, workspace[0]->Y + 468 * ratio_y),
				Point(workspace[0]->X + 361 * ratio_x, workspace[0]->Y + 465 * ratio_y),
				Point(workspace[0]->X + 360 * ratio_x, workspace[0]->Y + 462 * ratio_y),
				Point(workspace[0]->X + 358 * ratio_x, workspace[0]->Y + 460 * ratio_y),
				Point(workspace[0]->X + 358 * ratio_x, workspace[0]->Y + 457 * ratio_y),
				Point(workspace[0]->X + 356 * ratio_x, workspace[0]->Y + 455 * ratio_y),
				Point(workspace[0]->X + 355 * ratio_x, workspace[0]->Y + 452 * ratio_y),
				Point(workspace[0]->X + 355 * ratio_x, workspace[0]->Y + 449 * ratio_y),
				Point(workspace[0]->X + 355 * ratio_x, workspace[0]->Y + 447 * ratio_y),
				Point(workspace[0]->X + 353 * ratio_x, workspace[0]->Y + 442 * ratio_y),
				Point(workspace[0]->X + 351 * ratio_x, workspace[0]->Y + 440 * ratio_y),
				Point(workspace[0]->X + 350 * ratio_x, workspace[0]->Y + 438 * ratio_y),
				Point(workspace[0]->X + 348 * ratio_x, workspace[0]->Y + 436 * ratio_y),
				Point(workspace[0]->X + 347 * ratio_x, workspace[0]->Y + 436 * ratio_y),
				Point(workspace[0]->X + 345 * ratio_x, workspace[0]->Y + 434 * ratio_y),
				Point(workspace[0]->X + 346 * ratio_x, workspace[0]->Y + 433 * ratio_y),
				Point(workspace[0]->X + 347 * ratio_x, workspace[0]->Y + 430 * ratio_y),
				Point(workspace[0]->X + 348 * ratio_x, workspace[0]->Y + 429 * ratio_y),
				Point(workspace[0]->X + 346 * ratio_x, workspace[0]->Y + 426 * ratio_y),
				Point(workspace[0]->X + 343 * ratio_x, workspace[0]->Y + 427 * ratio_y),
				Point(workspace[0]->X + 340 * ratio_x, workspace[0]->Y + 428 * ratio_y),
				Point(workspace[0]->X + 337 * ratio_x, workspace[0]->Y + 428 * ratio_y),
				Point(workspace[0]->X + 336 * ratio_x, workspace[0]->Y + 430 * ratio_y),
				Point(workspace[0]->X + 333 * ratio_x, workspace[0]->Y + 432 * ratio_y),
				Point(workspace[0]->X + 330 * ratio_x, workspace[0]->Y + 432 * ratio_y),
				Point(workspace[0]->X + 326 * ratio_x, workspace[0]->Y + 433 * ratio_y),
				Point(workspace[0]->X + 325 * ratio_x, workspace[0]->Y + 432 * ratio_y),
				Point(workspace[0]->X + 323 * ratio_x, workspace[0]->Y + 432 * ratio_y),
				Point(workspace[0]->X + 322 * ratio_x, workspace[0]->Y + 431 * ratio_y),
				Point(workspace[0]->X + 325 * ratio_x, workspace[0]->Y + 429 * ratio_y),
				Point(workspace[0]->X + 326 * ratio_x, workspace[0]->Y + 429 * ratio_y),
				Point(workspace[0]->X + 326 * ratio_x, workspace[0]->Y + 427 * ratio_y),
				Point(workspace[0]->X + 321 * ratio_x, workspace[0]->Y + 426 * ratio_y),
				Point(workspace[0]->X + 319 * ratio_x, workspace[0]->Y + 424 * ratio_y),
				Point(workspace[0]->X + 317 * ratio_x, workspace[0]->Y + 427 * ratio_y),
				Point(workspace[0]->X + 317 * ratio_x, workspace[0]->Y + 424 * ratio_y),
				Point(workspace[0]->X + 317 * ratio_x, workspace[0]->Y + 422 * ratio_y),
				Point(workspace[0]->X + 314 * ratio_x, workspace[0]->Y + 421 * ratio_y),
				Point(workspace[0]->X + 312 * ratio_x, workspace[0]->Y + 421 * ratio_y),
				Point(workspace[0]->X + 310 * ratio_x, workspace[0]->Y + 421 * ratio_y),
				Point(workspace[0]->X + 309 * ratio_x, workspace[0]->Y + 419 * ratio_y),
				Point(workspace[0]->X + 310 * ratio_x, workspace[0]->Y + 418 * ratio_y),
				Point(workspace[0]->X + 311 * ratio_x, workspace[0]->Y + 417 * ratio_y),
				Point(workspace[0]->X + 311 * ratio_x, workspace[0]->Y + 414 * ratio_y),
				Point(workspace[0]->X + 311 * ratio_x, workspace[0]->Y + 411 * ratio_y),
				Point(workspace[0]->X + 309 * ratio_x, workspace[0]->Y + 409 * ratio_y),
				Point(workspace[0]->X + 307 * ratio_x, workspace[0]->Y + 407 * ratio_y),
				Point(workspace[0]->X + 303 * ratio_x, workspace[0]->Y + 406 * ratio_y),
				Point(workspace[0]->X + 302 * ratio_x, workspace[0]->Y + 406 * ratio_y),
				Point(workspace[0]->X + 298 * ratio_x, workspace[0]->Y + 404 * ratio_y),
				Point(workspace[0]->X + 295 * ratio_x, workspace[0]->Y + 404 * ratio_y),
				Point(workspace[0]->X + 293 * ratio_x, workspace[0]->Y + 406 * ratio_y),
				Point(workspace[0]->X + 289 * ratio_x, workspace[0]->Y + 406 * ratio_y),
				Point(workspace[0]->X + 286 * ratio_x, workspace[0]->Y + 406 * ratio_y),
				Point(workspace[0]->X + 282 * ratio_x, workspace[0]->Y + 406 * ratio_y),
				Point(workspace[0]->X + 279 * ratio_x, workspace[0]->Y + 406 * ratio_y),
				Point(workspace[0]->X + 277 * ratio_x, workspace[0]->Y + 406 * ratio_y),
				Point(workspace[0]->X + 273 * ratio_x, workspace[0]->Y + 404 * ratio_y),
				Point(workspace[0]->X + 269 * ratio_x, workspace[0]->Y + 406 * ratio_y),
				Point(workspace[0]->X + 265 * ratio_x, workspace[0]->Y + 406 * ratio_y),
				Point(workspace[0]->X + 260 * ratio_x, workspace[0]->Y + 405 * ratio_y),
				Point(workspace[0]->X + 256 * ratio_x, workspace[0]->Y + 404 * ratio_y),
				Point(workspace[0]->X + 252 * ratio_x, workspace[0]->Y + 404 * ratio_y),
				Point(workspace[0]->X + 249 * ratio_x, workspace[0]->Y + 403 * ratio_y),
				Point(workspace[0]->X + 247 * ratio_x, workspace[0]->Y + 402 * ratio_y),
				Point(workspace[0]->X + 245 * ratio_x, workspace[0]->Y + 401 * ratio_y),
				Point(workspace[0]->X + 241 * ratio_x, workspace[0]->Y + 401 * ratio_y),
				Point(workspace[0]->X + 240 * ratio_x, workspace[0]->Y + 404 * ratio_y),
				Point(workspace[0]->X + 240 * ratio_x, workspace[0]->Y + 405 * ratio_y),
				Point(workspace[0]->X + 238 * ratio_x, workspace[0]->Y + 408 * ratio_y),
				Point(workspace[0]->X + 241 * ratio_x, workspace[0]->Y + 410 * ratio_y),
				Point(workspace[0]->X + 243 * ratio_x, workspace[0]->Y + 412 * ratio_y),
				Point(workspace[0]->X + 241 * ratio_x, workspace[0]->Y + 413 * ratio_y),
				Point(workspace[0]->X + 240 * ratio_x, workspace[0]->Y + 413 * ratio_y),
				Point(workspace[0]->X + 238 * ratio_x, workspace[0]->Y + 412 * ratio_y),
				Point(workspace[0]->X + 236 * ratio_x, workspace[0]->Y + 411 * ratio_y),
				Point(workspace[0]->X + 234 * ratio_x, workspace[0]->Y + 411 * ratio_y),
				Point(workspace[0]->X + 232 * ratio_x, workspace[0]->Y + 413 * ratio_y),
				Point(workspace[0]->X + 232 * ratio_x, workspace[0]->Y + 417 * ratio_y),
				Point(workspace[0]->X + 232 * ratio_x, workspace[0]->Y + 418 * ratio_y),
				Point(workspace[0]->X + 230 * ratio_x, workspace[0]->Y + 418 * ratio_y),
				Point(workspace[0]->X + 228 * ratio_x, workspace[0]->Y + 419 * ratio_y),
				Point(workspace[0]->X + 225 * ratio_x, workspace[0]->Y + 419 * ratio_y),
				Point(workspace[0]->X + 226 * ratio_x, workspace[0]->Y + 423 * ratio_y),
				Point(workspace[0]->X + 229 * ratio_x, workspace[0]->Y + 426 * ratio_y),
				Point(workspace[0]->X + 232 * ratio_x, workspace[0]->Y + 431 * ratio_y),
				Point(workspace[0]->X + 229 * ratio_x, workspace[0]->Y + 435 * ratio_y),
				Point(workspace[0]->X + 222 * ratio_x, workspace[0]->Y + 435 * ratio_y),
				Point(workspace[0]->X + 220 * ratio_x, workspace[0]->Y + 432 * ratio_y),
				Point(workspace[0]->X + 216 * ratio_x, workspace[0]->Y + 432 * ratio_y),
				Point(workspace[0]->X + 214 * ratio_x, workspace[0]->Y + 433 * ratio_y),
				Point(workspace[0]->X + 211 * ratio_x, workspace[0]->Y + 429 * ratio_y),
				Point(workspace[0]->X + 209 * ratio_x, workspace[0]->Y + 426 * ratio_y),
				Point(workspace[0]->X + 208 * ratio_x, workspace[0]->Y + 422 * ratio_y),
				Point(workspace[0]->X + 205 * ratio_x, workspace[0]->Y + 422 * ratio_y),
				Point(workspace[0]->X + 201 * ratio_x, workspace[0]->Y + 422 * ratio_y),
				Point(workspace[0]->X + 199 * ratio_x, workspace[0]->Y + 419 * ratio_y),
				Point(workspace[0]->X + 196 * ratio_x, workspace[0]->Y + 417 * ratio_y),
				Point(workspace[0]->X + 192 * ratio_x, workspace[0]->Y + 418 * ratio_y),
				Point(workspace[0]->X + 189 * ratio_x, workspace[0]->Y + 418 * ratio_y),
				Point(workspace[0]->X + 187 * ratio_x, workspace[0]->Y + 418 * ratio_y),
				Point(workspace[0]->X + 185 * ratio_x, workspace[0]->Y + 416 * ratio_y),
				Point(workspace[0]->X + 183 * ratio_x, workspace[0]->Y + 413 * ratio_y),
				Point(workspace[0]->X + 181 * ratio_x, workspace[0]->Y + 410 * ratio_y),
				Point(workspace[0]->X + 181 * ratio_x, workspace[0]->Y + 408 * ratio_y),
				Point(workspace[0]->X + 179 * ratio_x, workspace[0]->Y + 403 * ratio_y),
				Point(workspace[0]->X + 176 * ratio_x, workspace[0]->Y + 400 * ratio_y),
				Point(workspace[0]->X + 173 * ratio_x, workspace[0]->Y + 398 * ratio_y),
				Point(workspace[0]->X + 170 * ratio_x, workspace[0]->Y + 395 * ratio_y),
				Point(workspace[0]->X + 168 * ratio_x, workspace[0]->Y + 396 * ratio_y),
				Point(workspace[0]->X + 165 * ratio_x, workspace[0]->Y + 394 * ratio_y),
				Point(workspace[0]->X + 165 * ratio_x, workspace[0]->Y + 391 * ratio_y),
				Point(workspace[0]->X + 162 * ratio_x, workspace[0]->Y + 389 * ratio_y),
				Point(workspace[0]->X + 160 * ratio_x, workspace[0]->Y + 391 * ratio_y),
				Point(workspace[0]->X + 156 * ratio_x, workspace[0]->Y + 392 * ratio_y),
				Point(workspace[0]->X + 153 * ratio_x, workspace[0]->Y + 390 * ratio_y),
				Point(workspace[0]->X + 150 * ratio_x, workspace[0]->Y + 390 * ratio_y),
				Point(workspace[0]->X + 149 * ratio_x, workspace[0]->Y + 391 * ratio_y),
				Point(workspace[0]->X + 147 * ratio_x, workspace[0]->Y + 392 * ratio_y),
				Point(workspace[0]->X + 143 * ratio_x, workspace[0]->Y + 392 * ratio_y),
				Point(workspace[0]->X + 141 * ratio_x, workspace[0]->Y + 393 * ratio_y),
				Point(workspace[0]->X + 141 * ratio_x, workspace[0]->Y + 396 * ratio_y),
				Point(workspace[0]->X + 139 * ratio_x, workspace[0]->Y + 397 * ratio_y),
				Point(workspace[0]->X + 138 * ratio_x, workspace[0]->Y + 396 * ratio_y),
				Point(workspace[0]->X + 136 * ratio_x, workspace[0]->Y + 395 * ratio_y),
				Point(workspace[0]->X + 136 * ratio_x, workspace[0]->Y + 393 * ratio_y),
				Point(workspace[0]->X + 136 * ratio_x, workspace[0]->Y + 390 * ratio_y),
				Point(workspace[0]->X + 134 * ratio_x, workspace[0]->Y + 390 * ratio_y),
				Point(workspace[0]->X + 132 * ratio_x, workspace[0]->Y + 390 * ratio_y),
				Point(workspace[0]->X + 131 * ratio_x, workspace[0]->Y + 392 * ratio_y),
				Point(workspace[0]->X + 129 * ratio_x, workspace[0]->Y + 392 * ratio_y),
				Point(workspace[0]->X + 125 * ratio_x, workspace[0]->Y + 393 * ratio_y),
				Point(workspace[0]->X + 124 * ratio_x, workspace[0]->Y + 396 * ratio_y),
				Point(workspace[0]->X + 123 * ratio_x, workspace[0]->Y + 397 * ratio_y),
				Point(workspace[0]->X + 122 * ratio_x, workspace[0]->Y + 399 * ratio_y),
				Point(workspace[0]->X + 120 * ratio_x, workspace[0]->Y + 399 * ratio_y),
				Point(workspace[0]->X + 117 * ratio_x, workspace[0]->Y + 399 * ratio_y),
				Point(workspace[0]->X + 115 * ratio_x, workspace[0]->Y + 401 * ratio_y),
				Point(workspace[0]->X + 114 * ratio_x, workspace[0]->Y + 402 * ratio_y),
				Point(workspace[0]->X + 113 * ratio_x, workspace[0]->Y + 403 * ratio_y),
				Point(workspace[0]->X + 115 * ratio_x, workspace[0]->Y + 406 * ratio_y),
				Point(workspace[0]->X + 116 * ratio_x, workspace[0]->Y + 408 * ratio_y),
				Point(workspace[0]->X + 116 * ratio_x, workspace[0]->Y + 411 * ratio_y),
				Point(workspace[0]->X + 114 * ratio_x, workspace[0]->Y + 412 * ratio_y),
				Point(workspace[0]->X + 114 * ratio_x, workspace[0]->Y + 413 * ratio_y),
				Point(workspace[0]->X + 116 * ratio_x, workspace[0]->Y + 416 * ratio_y),
				Point(workspace[0]->X + 118 * ratio_x, workspace[0]->Y + 417 * ratio_y),
				Point(workspace[0]->X + 120 * ratio_x, workspace[0]->Y + 418 * ratio_y),
				Point(workspace[0]->X + 119 * ratio_x, workspace[0]->Y + 420 * ratio_y),
				Point(workspace[0]->X + 119 * ratio_x, workspace[0]->Y + 423 * ratio_y),
				Point(workspace[0]->X + 120 * ratio_x, workspace[0]->Y + 425 * ratio_y),
				Point(workspace[0]->X + 120 * ratio_x, workspace[0]->Y + 429 * ratio_y),
				Point(workspace[0]->X + 118 * ratio_x, workspace[0]->Y + 429 * ratio_y),
				Point(workspace[0]->X + 116 * ratio_x, workspace[0]->Y + 429 * ratio_y),
				Point(workspace[0]->X + 115 * ratio_x, workspace[0]->Y + 432 * ratio_y),
				Point(workspace[0]->X + 116 * ratio_x, workspace[0]->Y + 433 * ratio_y),
				Point(workspace[0]->X + 118 * ratio_x, workspace[0]->Y + 435 * ratio_y),
				Point(workspace[0]->X + 119 * ratio_x, workspace[0]->Y + 437 * ratio_y),
				Point(workspace[0]->X + 115 * ratio_x, workspace[0]->Y + 437 * ratio_y),
				Point(workspace[0]->X + 112 * ratio_x, workspace[0]->Y + 437 * ratio_y),
				Point(workspace[0]->X + 110 * ratio_x, workspace[0]->Y + 438 * ratio_y),
				Point(workspace[0]->X + 108 * ratio_x, workspace[0]->Y + 437 * ratio_y),
				Point(workspace[0]->X + 105 * ratio_x, workspace[0]->Y + 437 * ratio_y),
				Point(workspace[0]->X + 103 * ratio_x, workspace[0]->Y + 436 * ratio_y),
				Point(workspace[0]->X + 100 * ratio_x, workspace[0]->Y + 436 * ratio_y),
				Point(workspace[0]->X + 100 * ratio_x, workspace[0]->Y + 438 * ratio_y),
				Point(workspace[0]->X + 98 * ratio_x, workspace[0]->Y + 439 * ratio_y),
				Point(workspace[0]->X + 96 * ratio_x, workspace[0]->Y + 441 * ratio_y),
				Point(workspace[0]->X + 94 * ratio_x, workspace[0]->Y + 441 * ratio_y),
				Point(workspace[0]->X + 91 * ratio_x, workspace[0]->Y + 441 * ratio_y),
				Point(workspace[0]->X + 90 * ratio_x, workspace[0]->Y + 441 * ratio_y),
				Point(workspace[0]->X + 88 * ratio_x, workspace[0]->Y + 443 * ratio_y),
				Point(workspace[0]->X + 88 * ratio_x, workspace[0]->Y + 444 * ratio_y),
				Point(workspace[0]->X + 90 * ratio_x, workspace[0]->Y + 447 * ratio_y),
				Point(workspace[0]->X + 90 * ratio_x, workspace[0]->Y + 451 * ratio_y),
				Point(workspace[0]->X + 89 * ratio_x, workspace[0]->Y + 454 * ratio_y),
				Point(workspace[0]->X + 87 * ratio_x, workspace[0]->Y + 456 * ratio_y),
				Point(workspace[0]->X + 85 * ratio_x, workspace[0]->Y + 458 * ratio_y),
				Point(workspace[0]->X + 84 * ratio_x, workspace[0]->Y + 461 * ratio_y),
				Point(workspace[0]->X + 83 * ratio_x, workspace[0]->Y + 463 * ratio_y),
				Point(workspace[0]->X + 83 * ratio_x, workspace[0]->Y + 467 * ratio_y),
				Point(workspace[0]->X + 82 * ratio_x, workspace[0]->Y + 471 * ratio_y),
				Point(workspace[0]->X + 82 * ratio_x, workspace[0]->Y + 473 * ratio_y),
				Point(workspace[0]->X + 82 * ratio_x, workspace[0]->Y + 479 * ratio_y),
				Point(workspace[0]->X + 78 * ratio_x, workspace[0]->Y + 479 * ratio_y),
				Point(workspace[0]->X + 73 * ratio_x, workspace[0]->Y + 480 * ratio_y),
				Point(workspace[0]->X + 70 * ratio_x, workspace[0]->Y + 474 * ratio_y),
				Point(workspace[0]->X + 70 * ratio_x, workspace[0]->Y + 469 * ratio_y),
				Point(workspace[0]->X + 68 * ratio_x, workspace[0]->Y + 465 * ratio_y),
				Point(workspace[0]->X + 66 * ratio_x, workspace[0]->Y + 463 * ratio_y),
				Point(workspace[0]->X + 66 * ratio_x, workspace[0]->Y + 460 * ratio_y),
				Point(workspace[0]->X + 67 * ratio_x, workspace[0]->Y + 455 * ratio_y),
				Point(workspace[0]->X + 64 * ratio_x, workspace[0]->Y + 454 * ratio_y),
				Point(workspace[0]->X + 62 * ratio_x, workspace[0]->Y + 451 * ratio_y),
				Point(workspace[0]->X + 59 * ratio_x, workspace[0]->Y + 450 * ratio_y),
				Point(workspace[0]->X + 55 * ratio_x, workspace[0]->Y + 448 * ratio_y),
				Point(workspace[0]->X + 55 * ratio_x, workspace[0]->Y + 444 * ratio_y),
				Point(workspace[0]->X + 52 * ratio_x, workspace[0]->Y + 441 * ratio_y),
				Point(workspace[0]->X + 51 * ratio_x, workspace[0]->Y + 437 * ratio_y),
				Point(workspace[0]->X + 49 * ratio_x, workspace[0]->Y + 434 * ratio_y),
				Point(workspace[0]->X + 47 * ratio_x, workspace[0]->Y + 432 * ratio_y),
				Point(workspace[0]->X + 45 * ratio_x, workspace[0]->Y + 430 * ratio_y),
				Point(workspace[0]->X + 43 * ratio_x, workspace[0]->Y + 428 * ratio_y),
				Point(workspace[0]->X + 43 * ratio_x, workspace[0]->Y + 425 * ratio_y),
				Point(workspace[0]->X + 41 * ratio_x, workspace[0]->Y + 423 * ratio_y),
				Point(workspace[0]->X + 40 * ratio_x, workspace[0]->Y + 422 * ratio_y),
				Point(workspace[0]->X + 38 * ratio_x, workspace[0]->Y + 420 * ratio_y),
				Point(workspace[0]->X + 36 * ratio_x, workspace[0]->Y + 418 * ratio_y),
				Point(workspace[0]->X + 35 * ratio_x, workspace[0]->Y + 417 * ratio_y),
				Point(workspace[0]->X + 33 * ratio_x, workspace[0]->Y + 417 * ratio_y),
				Point(workspace[0]->X + 33 * ratio_x, workspace[0]->Y + 414 * ratio_y),
				Point(workspace[0]->X + 32 * ratio_x, workspace[0]->Y + 410 * ratio_y),
				Point(workspace[0]->X + 33 * ratio_x, workspace[0]->Y + 407 * ratio_y),
				Point(workspace[0]->X + 33 * ratio_x, workspace[0]->Y + 404 * ratio_y),
				Point(workspace[0]->X + 32 * ratio_x, workspace[0]->Y + 402 * ratio_y),
				Point(workspace[0]->X + 32 * ratio_x, workspace[0]->Y + 400 * ratio_y),
				Point(workspace[0]->X + 31 * ratio_x, workspace[0]->Y + 399 * ratio_y),
				Point(workspace[0]->X + 31 * ratio_x, workspace[0]->Y + 396 * ratio_y),
				Point(workspace[0]->X + 30 * ratio_x, workspace[0]->Y + 394 * ratio_y),
				Point(workspace[0]->X + 29 * ratio_x, workspace[0]->Y + 393 * ratio_y),
				Point(workspace[0]->X + 29 * ratio_x, workspace[0]->Y + 389 * ratio_y),
				Point(workspace[0]->X + 30 * ratio_x, workspace[0]->Y + 386 * ratio_y),
				Point(0, workspace[0]->Y + 386 * ratio_y),
				Point(0, workspace[1]->Y),
			};
			grfx->FillPolygon(bg, Russia0);
			grfx->FillPolygon(bg, Russia1);
			grfx->FillPolygon(bg, Russia2);
			grfx->FillPolygon(bg, Russia3);
			//this->Text = ratio_x.ToString();
			PB_Playboard->Image = board;
		}

		private: System::Void MilitaryAvoidForm_Load(System::Object^ sender, System::EventArgs^ e) {
			draw();
		}
		private: System::Void MilitaryAvoidForm_SizeChanged(System::Object^ sender, System::EventArgs^ e) {
			draw();
		}
		private: System::Void PB_Playboard_MouseMove(System::Object^ sender, System::Windows::Forms::MouseEventArgs^ e) {
			//paint();
		}
		private: System::Void PB_Playboard_Paint(System::Object^ sender, System::Windows::Forms::PaintEventArgs^ e) {
			paint();
		}
	};
}
